### ISSUE TITLE
[Bug] Miner stops mining after a short time

### ISSUE THREAD

**Issue by kovart** [AleoHQ/snarkOS#1177] opened 2021-09-22 11:27 UTC
## 🐛 Bug Report

Aleo miner stops mining after 4-5 hours, no new blocks are mined after this time. 
Sometimes the only one block is mined in more than 12 hours. 
Similar behaviour I found with the node service.
**The issue is reproducible every time I run the service.**

HDD: 2% in use.
RAM: 12/32Gb in use.

NODE INFO:
{
  "is_miner": true,
  "is_syncing": true,
  "max_peers": 50,
  "min_peers": 20,
  "node_type": "Client",
  "version": "1.3.16"
}

## Steps to Reproduce

1. Run `systemctl run aleod-miner`
2. Wait 4-6 hours
3. Check the amount of mined blocks via https://api.nodes.guru/aleo_monitor.sh
4. Restart aleo-miner and make sure that it starts mining again

## Expected Behavior

Miner should mine blocks without restarts.

## Your Environment

Snarkos v. 1.3.16
Ubuntu 20.04 
rustc 1.55.0 (c8dfcfe04 2021-09-06)

**Comment by ljedrz** [comment] 2021-09-22 12:02
I noticed that the node in question was syncing blocks (`"is_syncing": true`); the mining process shouldn't start until the node is fully synced with the chain, so this is expected. Have you encountered this with a fully synced node?

**Comment by kovart** [comment] 2021-09-22 16:18
Hm... I started the miner when it was fully synced, but then after a while it is changed to "is_syncing": true.
Running `journalctl` shows the following log (a lot of messages):
```bash
Sep 22 18:14:30.786 DEBUG Received a 'block' message from 78.46.109.144:4131
Sep 22 18:14:30.793 DEBUG Received a 'getblocks' message from 95.111.239.25:4131
Sep 22 18:14:30.808 DEBUG Received a 'getsync' message from 95.111.239.25:4131
Sep 22 18:14:30.832 DEBUG Received a 'block' message from 65.108.0.48:4131
Sep 22 18:14:30.891 DEBUG Received a 'getblocks' message from 65.21.227.110:4131
Sep 22 18:14:30.922 DEBUG Received a 'block' message from 162.55.210.184:4131
Sep 22 18:14:30.938 DEBUG Sent a 'sync' message to 95.111.239.25:4131
Sep 22 18:14:30.938  INFO Got a block from 65.108.0.48:4131 (epoch 1632327256) with hash 7cea22c7... (current head 413672)
Sep 22 18:14:30.938 DEBUG Processing a block that is an unknown orphan
Sep 22 18:14:30.938 DEBUG Propagating a block to peers
Sep 22 18:14:30.939 DEBUG Sent a 'block' message to 194.163.155.91:4131
Sep 22 18:14:30.939 DEBUG Sent a 'block' message to 188.242.55.34:4131
Sep 22 18:14:30.939 DEBUG Sent a 'block' message to 49.12.210.52:4131
Sep 22 18:14:30.939 DEBUG Sent a 'block' message to 65.21.227.110:4131
Sep 22 18:14:30.939 DEBUG Sent a 'block' message to 178.18.247.92:4131
Sep 22 18:14:30.939 DEBUG Sent a 'block' message to 161.35.90.73:4131
Sep 22 18:14:30.939 DEBUG Sent a 'block' message to 136.244.89.231:4131
Sep 22 18:14:30.939 DEBUG Sent a 'block' message to 159.89.123.121:4131
Sep 22 18:14:30.939 DEBUG Sent a 'block' message to 162.55.210.184:4131
Sep 22 18:14:30.939 DEBUG Sent a 'block' message to 84.252.73.147:4131
Sep 22 18:14:30.939 DEBUG Sent a 'block' message to 185.139.68.115:4131
Sep 22 18:14:30.939 DEBUG Sent a 'block' message to 136.243.7.91:4131
Sep 22 18:14:30.939 DEBUG Sent a 'block' message to 65.21.183.201:4131
Sep 22 18:14:30.939 DEBUG Sent a 'block' message to 78.141.208.184:4131
Sep 22 18:14:30.939 DEBUG Sent a 'block' message to 78.46.109.144:4131
```
It looks like it's syncing

**Comment by kovart** [comment] 2021-09-23 06:45
Yesterday night I run the miner, It was `"is syncing": true` and 1 block was mined in next 5 minutes. This morning, since that time, it mined 4 blocks and `is_syncing` is still `true`.

**Comment by ljedrz** [comment] 2021-09-23 07:34
> It looks like it's syncing

those logs indicate that the node is providing sync blocks to other peers; as for intermittent syncing and mining, as long as your block height is growing, it should be fine - your node might just be altering between other prospect canon tips.

**Comment by kovart** [comment] 2021-09-24 11:28
I think I found the real issue. Node is not syncing but it shows that it is syncing.
I run the node yesterday evening but it is almost on the same height as yerterday (413886)

**Comment by kovart** [comment] 2021-09-25 20:36
I replaced blockchain with a snapshot from nodes.guru (height 416552) and It started syncing again. 
But, since a few minutes, it got stuck at 419285 and new height is almost not updating (current height is 421021).

**Comment by tyan-boot** [comment] 2021-10-11 02:27
Did you see some log like `WARN Miner has failed to mine a block 10 times. Shutting down miner.`?

**Comment by ljedrz** [comment] 2021-10-11 08:10
Ok, I think I know what the issue is.

**Comment by ljedrz** [comment] 2021-10-13 07:54
This issue should now be fixed in `staging`, but I'll keep it open in case there were other reasons behind the miner stopping.

**Closed as completed** 2022-01-06 02:03 UTC
Labels: bug, likely fixed, mining
