### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by makefriendwithtime** [AleoHQ/snarkOS#1609] opened 2022-02-05 17:16 UTC
I configured it according to the snarkOS installation instructions, and started run-miner.sh to prompt the following questions:
Failed to get challenge response from 137.184.202.162:4132: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }

**Comment by ljedrz** [comment] 2022-02-07 11:09
Duplicate of https://github.com/AleoHQ/snarkOS/issues/1358.

**Closed as completed by ljedrz** 2022-02-07 11:09 UTC
Labels: bug, duplicate, network, testnet2
