### ISSUE TITLE
[Bug] Operator gets error : thread 'tokio-runtime-worker' panicked at 'capacity overflow'

### ISSUE THREAD

**Issue by davaymne** [AleoHQ/snarkOS#1551] opened 2022-01-13 12:34 UTC
snarkOS: af07c7f

There are 2 errors:
 - Operator fails and reboots with notification: `memory allocation of 16817298866400384360 bytes failed`
 - In the logs I can observe `thread 'tokio-runtime-worker' panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:562:5`

**Comment by ljedrz** [comment] 2022-01-13 14:55
Duplicate of https://github.com/AleoHQ/snarkOS/issues/1534.

**Closed as completed by ljedrz** 2022-01-13 14:55 UTC
Labels: bug, duplicate, crash, testnet2
