### ISSUE TITLE
[Bug] thread 'main' panicked at 'Failed to start the node: Loaded a ledger with inconsistent state (194611 != 194612) (unable to automatically resolve)', src/main.rs:64:28

### ISSUE THREAD

**Issue by thewebscraping** [AleoHQ/snarkOS#1626] opened 2022-02-09 23:58 UTC
## 🐛 Bug Report

thread 'main' panicked at 'Failed to start the node: Loaded a ledger with inconsistent state (194611 != 194612) (unable to automatically resolve)', src/main.rs:64:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

## Expected Behavior

I can't start sync and miner with the bugs, please help.

## Your Environment

- snarkos 2.0.0

- rustc 1.58.1 (db9d1b20b 2022-01-20)

- Ubuntu 20.04 LTS (Focal Fossa)

**Comment by ljedrz** [comment] 2022-02-10 07:12
Closing as a duplicate of https://github.com/AleoHQ/snarkOS/issues/1550.

**Closed as completed by ljedrz** 2022-02-10 07:12 UTC
Labels: bug, duplicate, storage, crash, testnet2
