### ISSUE TITLE
Aleo mining is centralized

### ISSUE THREAD

**Issue by crabvk** [AleoHQ/snarkOS#1472] opened 2021-12-20 06:48 UTC
According to [aleochain.io](https://aleochain.io/) there are currently 6984 nodes in the network.
According to the [leaderboard](https://www.aleo.network/leaderboard) almost all blocks mined by
<details>
  <summary>a very few nodes:</summary>
<pre>
<code>

Pos	Address								Score	%
1	aleo1nuhl5vf8xdldzxsfnzsnsdgfvqkuufzex2598fzjuxkq2qrl5qzqupr666	19863	45.7
2	aleo1gqa7nht8lv93ksgmfy8hnz028r776evnv5kllkcsx2ycek5ryq9suprafw	12082	27.8
3	aleo1dyg9nrxpyfj06nphyqgvezh3tqg8eqjn69ee0r5x7wjj4jwyn5gqsavly8	3834	8.8
4	aleo1vlunzlxyrv42fx622t2jlu39j5ucrd4zsq32s63hy3v5kdmphgps2qyy0l	1612	3.7
5	aleo1pa0ctcyettxqjqxt580dwd6v66taaq8ptft3l4623cw6m89rdq8qr39f0a	1285	2.9
6	aleo1ykm8wqgp04y7rszqrxu9zpnz9q8v00gcrmd7jsw97ve3dw6tmuxq8jawrk	1038	2.3
7	aleo19p8n0lufzwxyqzj4fxxawhvphurvlxtyu9gtql87jrmhqhv5x5xsryj8sm	322	0.74
8	aleo1vmwkf4plvkjvj4zmgsvhqdajlfxhyemafx4hysgyu8heh8qp4g9q24523q	291	0.67
9	aleo19f2g4gdnay2d49lm9mgzw90pr6utzjrxsrhvyl69jc0s62kkfqxsq32jae	133	0.30
10	aleo1trnczew3y95uka8zwtnqt9c8u8wtsh8xxg5s6zh0vn8jtgg96uyqrac55e	124	0.28
11	aleo19jj0r0grw3sq9mhy98zeeq76fsnr6v78wdwdjtdhzegpjfc3jcyqq7qp24	106	0.24
12	aleo106tgtz2zwrlgzke7u92epahqr769r6dqs0dahmj0ph69ttvx5szqlnsdzs	99	0.22
13	aleo128u0yr90u6v8fyhftqve3yxkdf5v2ectw3d9hxmvvhhtvh8a4g8sv8m9as	82	0.18
14	aleo1lyrphvgpz7fwvlnafuxpv4szf0eskmhe965dt5ltlgvvdsthm5zqasa3mv	61	0.14
15	aleo1axgv7tywqpe7a0e6t6k57kgtwtrk24kh7n6ph44mnudtxj628qgqhynnq7	51	0.11
16	aleo1l5t08cheww0u3qf54tgdvtcwl38z4nzthvht8e8g2c8ehmaf6gps2slpfz	40	0.09
17	aleo145gftncgsrluj3hdsw4k9uxz4y6ynkaddlxgn79v2ahqxdrywyfqvurv40	39	0.08
18	aleo129tdtyc8ylaytu6psks9f69lhk3cyc0svf766r8lnvmymd0cqv8q4vvz3z	30	0.06
19	aleo12233t3ml7zfmxvqrhctjjkxr4j0vene79wt73gxxgrh3myldlczqpq6jp8	24	0.05
20	aleo1344npuwawy3nuc5uj5j6jkqvaduc2f4m0k9fj34fjv2ptffs4yyqvhwxqj	22	0.05
21	aleo1xkpnrm4j95l72w2vecx28tylzn62e4w0ahgrsxsmhcc2yw9nqspq8zz0g7	17	0.03
...
</code>
</pre>
</details>

How many nodes first two addresses have idk, but it's 0.028% of all nodes that mined 73.5% of all blocks.

**Comment by podlodkin** [comment] 2021-12-20 06:59
100% agree. That is not the future that we want :)

**Comment by AndiCapital** [comment] 2021-12-20 07:01
The characteristics are higher than those stated.
0 blocks.

**Comment by alexander-konovalov** [comment] 2021-12-20 07:02
I agree with you dude, this is unacceptable

**Comment by hap50** [comment] 2021-12-20 07:05
> According to [aleochain.io](https://aleochain.io/) there are currently 6984 nodes in the network. According to the [leaderboard](https://www.aleo.network/leaderboard) almost all blocks mined by
> a very few nodes:
> 
> How many nodes first two addresses has idk, but it's 73.5% of all blocks mined.

**Comment by hap50** [comment] 2021-12-20 07:06
Absolutly agree with crabvk

**Comment by Madbustazz** [comment] 2021-12-20 07:10
D-decentralization... 0 block on my miner

**Comment by crabvk** [comment] 2021-12-20 07:13
> D-decentralization... 0 block on my miner

Same as 83.5% of all nodes, 0 blocks mined.

**Comment by cryptoved** [comment] 2021-12-20 07:21
Let's make Aleo decentralised! Interesting to see feedback from team.

**Comment by goomario** [comment] 2021-12-20 08:00
Long forks always appear. The longest one has been found to be the rollback of 55 blocks.
My node submitted more than 20 proofs, but they were all forked.

**Comment by goomario** [comment] 2021-12-20 08:02
> 

My node submitted more than 20 proofs, but they were all forked.

**Comment by nukodim** [comment] 2021-12-20 08:24
That's true. That's not that the team wrote about in announcements

**Comment by Skill127** [comment] 2021-12-20 08:55
I totally agree!!! The server is better than the recommended requirements. 2 weeks of continuous operation of 0 blocks. All blocks are taken by several people....

**Comment by MichaelKonovalov** [comment] 2021-12-20 11:53
Aleo mining is centralized, but project is 100 % decentralized. ha-ha-ha

**Comment by howardwu** [comment] 2021-12-20 13:06
Hundreds of mining nodes have successfully mined blocks - the testnet has demonstrated itself to be permissionless and decentralized. However, I do agree that the testnet could be more decentralized, and the core team is working (with community contributors) to introduce new avenues for mining. As a testnet, you should expect protocol changes that will impact how difficulty is targeted, and how rewards are distributed.

Closing as the discussion is unrelated to specific snarkOS technical issues.

**Closed as completed by howardwu** 2021-12-20 13:06 UTC
Labels: bug, mining, testnet2

**Comment by crabvk** [comment] 2021-12-20 13:33
@howardwu 
> Hundreds of mining nodes have successfully mined blocks

So what? I'm talking about proportion of mined blocks here. This is just hilarious how it is now. And even the hundreds with > 0 mined blocks is only 16.5% of all nodes.

> the testnet has demonstrated itself to be permissionless and decentralized.

Permissionless - yes, but mining is not decentralized (yet).
I can't tell you technically what issue is, but it seems like the whole thing is broken and you're trying to overcome it with another centralization (pools).

**Comment by apruden2008** [comment] 2021-12-20 16:27
@crabvk this is open source code. If you think you can fix it, we're open to reviewing any proposal. If you think you can do it better, feel free and fork the code and let's see. 

This is a testnet. It's centralized by design. And the point is to allow us to learn the lessons we need to know to get to mainnet. 

Incentivized testnets are bug bounties/work bounties. Turned out, a few folks invested a lot of time, effort and capital to win blocks, AND it's true they are taking advantage of some bugs. Bugs happen all the time in software development. And having an incentivized testnet is how we identify those bugs. And we're working to address them. In addition, we're working to address the relative disparity between the top miners and everyone else (which again, was not something we anticipated).

**Comment by crabvk** [comment] 2021-12-20 16:35
@apruden2008 Thanks for the detailed and clear answer. Now I see that you know about the bug. Do you have an issue for the bug you described?

**Comment by apruden2008** [comment] 2021-12-20 16:42
No, not yet. Planning to today. However, the issue is right here: https://github.com/AleoHQ/snarkOS/blob/8bc3871eebdcf2eca56499500195074884007b8a/storage/src/state/ledger.rs#L608

Manipulating the timestamp enables you to create arbitrarily heavy blocks. See a longer discussion here:
https://discord.com/channels/700454073459015690/836382809035636737/922345318228586536
