### ISSUE TITLE
[bug]thread 'main' panicked at 'Failed to start the node: Loaded a ledger with inconsistent state (297 != 298) (unable to automatically resolve)'

### ISSUE THREAD

**Issue by Staking7pc** [AleoHQ/snarkOS#1359] opened 2021-12-01 03:31 UTC
## 🐛 Bug Report

thread 'main' panicked at 'Failed to start the node: Loaded a ledger with inconsistent state (297 != 298) (unable to automatically resolve)'

Your Aleo miner address is aleo1plnv0z7thr8qgzw2vugjlwdjket9ls85dmqqmc7xhnfshzttqgzswy9j52
   
My node stopped syncing

## Steps to Reproduce

I am not sure if I can reproduce this 

## Expected Behavior

after running the miner, I expected there should be an uninterrupted flow instead it was stopped

## Your Environment

-  snarkos 2.0.0
- rustc 1.56.1 (59eed8a2a 2021-11-01)
- ubuntu 20.04
- 
Dedicated server

     * AMD Ryzen 7 1700X
     * 2x SSD SATA 512 GB
     * 4x RAM 16384 MB DDR4

**Comment by Staking7pc** [comment] 2021-12-01 03:39
Here is what i get when i run with RUST_BACKTRACE=1


thread 'main' panicked at 'Failed to start the node: Loaded a ledger with inconsistent state (297 != 298) (unable to automatically resolve)', src/main.rs:52:28
stack backtrace:
   0: rust_begin_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
   2: core::result::unwrap_failed
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/result.rs:1617:5
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   4: tokio::park::thread::CachedParkThread::block_on
   5: tokio::runtime::thread_pool::ThreadPool::block_on
   6: tokio::runtime::Runtime::block_on
   7: snarkos::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by Staking7pc** [comment] 2021-12-01 03:40
Here is what i get when i run with RUST_BACKTRACE=full



Reading package lists... Done
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55d4b17eee9c - core::fmt::write::h31b9cd1bedd7ea38
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/fmt/mod.rs:1150:17
   5:     0x55d4b1e21d55 - std::io::Write::write_fmt::h1fdf66f83f70913e
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/io/mod.rs:1667:15
   6:     0x55d4b1e2a270 - std::sys_common::backtrace::_print::he7ac492cd19c3189
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55d4b1e2a270 - std::sys_common::backtrace::print::hba20f8920229d8e8
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55d4b1e2a270 - std::panicking::default_hook::{{closure}}::h714d63979ae18678
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:210:50
   9:     0x55d4b1e2aaba - std::panicking::default_hook::hf1afb64e69563ca8
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:227:9
  10:     0x55d4b1e2aaba - std::panicking::rust_panic_with_hook::h02231a501e274a13
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:624:17
  11:     0x55d4b1e2a3ba - std::panicking::begin_panic_handler::{{closure}}::h5b5e738edf361af7
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:521:13
  12:     0x55d4b1e28ff4 - std::sys_common::backtrace::__rust_end_short_backtrace::h601a115def7987b1
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55d4b1e2a33d - rust_begin_unwind
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517:5
  14:     0x55d4b110cc81 - core::panicking::panic_fmt::h7a58c8fffc5559a4
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101:14
  15:     0x55d4b110cd73 - core::result::unwrap_failed::h1036b5c6eb8030dd
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/result.rs:1617:5
  16:     0x55d4b166b825 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h52ac4f961fe51144
  17:     0x55d4b14317f7 - tokio::park::thread::CachedParkThread::block_on::h6bf124b8bc97c90f
  18:     0x55d4b1529e4c - tokio::runtime::thread_pool::ThreadPool::block_on::h9723862a6cb7bb69
  19:     0x55d4b181050e - tokio::runtime::Runtime::block_on::hfcde78f539dba3d1
  20:     0x55d4b1734d82 - snarkos::main::h6b4474eb30e3d716
  21:     0x55d4b12fe7d3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h85ecf8b89c491ae8
  22:     0x55d4b180ff9d - std::rt::lang_start::{{closure}}::h749198a52febab98
  23:     0x55d4b1e2b21f - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2790017aba790142
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:259:13
  24:     0x55d4b1e2b21f - std::panicking::try::do_call::hd5d0fbb7d2d2d85d
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
  25:     0x55d4b1e2b21f - std::panicking::try::h675520ee37b0fdf7
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
  26:     0x55d4b1e2b21f - std::panic::catch_unwind::h803430ea0284ce79
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14
  27:     0x55d4b1e2b21f - std::rt::lang_start_internal::{{closure}}::h3a398a8154de3106
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:45:48
  28:     0x55d4b1e2b21f - std::panicking::try::do_call::hf60f106700df94b2
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
  29:     0x55d4b1e2b21f - std::panicking::try::hb2022d2bc87a9867
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
  30:     0x55d4b1e2b21f - std::panic::catch_unwind::hbf801c9d61f0c2fb
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14
  31:     0x55d4b1e2b21f - std::rt::lang_start_internal::hdd488b91dc742b96
                               at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:45:20
  32:     0x55d4b1734f12 - main
  33:     0x7f4d9aa780b3 - __libc_start_main
  34:     0x55d4b117b13e - _start
  35:                0x0 - <unknown>

**Comment by ljedrz** [comment] 2021-12-06 09:12
Closing the issue as a duplicate of https://github.com/AleoHQ/snarkOS/issues/1345.

**Closed as completed by ljedrz** 2021-12-06 09:12 UTC
Labels: bug, duplicate, storage, testnet2
