### ISSUE TITLE
snarkos miner stats error

### ISSUE THREAD

**Issue by CrazyAz10** [AleoHQ/snarkOS#1499] opened 2021-12-24 03:49 UTC
I carry out orders： snarkos miner stats aleo1xxxxxx

Output results：
2021-12-24T03:27:04.520282Z TRACE [Read-Only] Ledger successfully loaded at block 77940
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IO error: While lock file: /root/.aleo/storage/prover-2/LOCK: Resource temporarily unavailable', src/node.rs:423:111
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by ljedrz** [comment] 2021-12-24 12:14
Duplicate of https://github.com/AleoHQ/snarkOS/issues/1354.

**Closed as completed by ljedrz** 2021-12-24 12:14 UTC
Labels: bug
