### ISSUE TITLE
[Bug] run-client.sh fails to run on windows

### ISSUE THREAD

**Issue by Evan-Kim2028** [AleoHQ/snarkOS#1361] opened 2021-12-01 04:29 UTC
## 🐛 Bug Report

(Write your description here)

## Steps to Reproduce

1. rune `run-client.sh` in cmd

## Your Environment

- 
- 
-

**Comment by kiennd** [comment] 2021-12-01 19:21
I ran on windows and i got this error message:
standard_init_linux.go:228: exec user process caused: no such file or directory

**Comment by ljedrz** [comment] 2021-12-06 09:18
This is because Windows doesn't handle `.sh` files by default; I currently don't have access to a Windows PC, but I think you need to compile the node manually. A windows `cmd` script might be added in the future.

This should probably be addressed in the `README`.

**Comment by ljedrz** [comment] 2021-12-14 11:06
Removing the `bug` label, as bash scripts not working under Windows is not a bug.

**Comment by ljedrz** [comment] 2022-02-08 12:00
Closing in favor of https://github.com/AleoHQ/snarkOS/issues/1620.

**Closed as completed by ljedrz** 2022-02-08 12:00 UTC
Labels: testnet2, windows, scripts
