### ISSUE TITLE
bug in windows

### ISSUE THREAD

**Issue by feiyiban** [AleoHQ/snarkOS#1813] opened 2022-06-29 15:32 UTC
![b24b96ff058696f7649683be6fec338](https://user-images.githubusercontent.com/15224713/176476708-a0bbf4c9-8306-4b2b-980c-862dfd632adb.png)

**Comment by goodbabynow** [comment] 2022-06-30 09:43
no body care this???

**Comment by ljedrz** [comment] 2022-06-30 15:41
This isn't necessarily a bug, we've had Windows users before; Windows compilation is just tricky and currently not documented. Feel free to contribute installation instructions if you manage to do it.

Closing as a duplicate of https://github.com/AleoHQ/snarkOS/issues/1620.

**Closed as completed by ljedrz** 2022-06-30 15:41 UTC
Labels: duplicate, windows, compilation
