### ISSUE TITLE
[Bug] Unable to reach the beacon

### ISSUE THREAD

**Issue by cktkdgh1219** [AleoHQ/snarkOS#2040] opened 2022-11-09 09:11 UTC
## 🐛 Bug Report

2022-11-09T09:08:26.577993Z ERROR Unable to reach '159.65.195.225:4133': 'Elapsed(())'
2022-11-09T09:08:35.368718Z DEBUG Peers: []
2022-11-09T09:08:35.368822Z TRACE Skipping connection request to '159.65.195.225:4133' (tried 9 secs ago)
2022-11-09T09:08:38.358692Z  WARN [PuzzleRequest] No connected beacons
2022-11-09T09:08:44.370579Z DEBUG Peers: []
2022-11-09T09:08:44.370692Z TRACE Skipping connection request to '159.65.195.225:4133' (tried 18 secs ago)
2022-11-09T09:08:50.360690Z  WARN [PuzzleRequest] No connected beacons
2022-11-09T09:08:53.372062Z DEBUG Peers: []
2022-11-09T09:08:53.372151Z TRACE Skipping connection request to '159.65.195.225:4133' (tried 27 secs ago)

Received advice yesterday and reinstalled today. The installation went well, but the current message is displayed and block synchronization is not performed. Both public and private IP messages are displayed. When the 4133 port of the IP is checked with hping3, the connection is confirmed normally.
Do you have any solution for that problem?

## Your Environment

- 
- 2.0.2
- 
- 1.65.0
-

**Comment by niklaslong** [comment] 2022-11-09 10:05
The error would suggest the attempt to connect via tcp is timing out; this could be a number of things (assuming port 4133 is open, which it seems to be from the logs):

- your internet connection,
- the beacon peer limits being reached and it therefore being unable to accept new connections,

We'll investigate and get back to you asap; in the meantime you can try restarting your node periodically to see if you can get through.

**Comment by cktkdgh1219** [comment] 2022-11-09 10:27
@niklaslong Let's restart the node and wait.
If the problem is solved, please leave a reply, thank you.

**Comment by beck-8** [comment] 2022-11-09 15:08
https://github.com/AleoHQ/snarkOS/issues/2039
This is because this parameter is set incorrectly. It can be solved only by setting the parameter correctly and official upgrading the official version.

**Comment by pennchester** [comment] 2022-11-10 05:47
The latest code has been used, which is still the case

**Comment by Particaly** [comment] 2022-11-10 06:07
for me it turns to
![image](https://user-images.githubusercontent.com/28535489/201013576-db7713fd-0ccc-4741-ab80-17ee1edb2d79.png)

**Comment by niklaslong** [comment] 2022-11-10 07:39
@Particaly, this is a separate issue with a different cause. The beacon is dropping its connection to your node; this could be for a number of reasons:

- you're not running the latest version of snarkOS
- you have an issue with your chain state
- a connectivity issue (closed port, firewall etc...)

**Comment by niklaslong** [comment] 2022-11-10 07:41
@pennchester, what hardware and which commit are you running?

**Comment by pennchester** [comment] 2022-11-10 09:31
> 

@niklaslong ,
![image](https://user-images.githubusercontent.com/46217533/201052800-ab50fa2f-74d9-41c8-ae2d-d2abe8214a6e.png)
![image](https://user-images.githubusercontent.com/46217533/201053091-68039a48-90b1-4acd-bb51-283cee130808.png)

I used this :https://github.com/AleoHQ/snarkOS/commit/8c27c03963ce11d42cc80beef9437934a8d51956

**Comment by niklaslong** [comment] 2022-11-10 10:20
Could you try increasing the timeout locally, to see if this is the root cause? An example of how to do this can be found here: https://github.com/AleoHQ/snarkOS/pull/2041/files. The beacon is seeing connections currently; it may also be that your node is not executing the handshake quickly enough or network latency is too high.

**Comment by verynohair** [comment] 2022-11-11 01:00
The problem is still exists after build a release with the latest code.

And it works normally when it run on the cloud server with a static IP address.

But I cannot connect to the outbound peer in the local lan envrioment , however I can ping the ip address "159.65.195.225" in the same work machine.

**Comment by bingcongxihaha** [comment] 2022-11-11 12:15
I seem to have the same problem,These addresses cannot be telnet
![图片](https://user-images.githubusercontent.com/95521651/201338384-ac79e1b1-da7c-42f5-86d1-88b1699b8276.png)

**Comment by niklaslong** [comment] 2022-11-11 18:40
@bingcongxihaha this issue should be fixed now.

**Comment by sedasdas** [comment] 2022-11-12 21:36
For the same problem, confirm that the network is normal, the port is open, but the connection is often disconnected, and then automatically connected

**Comment by sedasdas** [comment] 2022-11-13 00:33
The bootstrp node is not stable enough

**Comment by sedasdas** [comment] 2022-11-13 00:47
![image](https://user-images.githubusercontent.com/13110234/201500293-2729d71c-62b8-4d23-bbd7-035cbcc1f971.png)
This happens after a while, later normal, and so on

**Comment by sedasdas** [comment] 2022-11-13 00:48
> 您能否尝试在本地增加超时，看看这是否是根本原因？可以在此处找到如何执行此操作的示例：https://github.com/AleoHQ/snarkOS/pull/2041/files。信标当前正在查看连接;也可能是因为您的节点执行握手的速度不够快或网络延迟太高。

Invalid confirmation

**Comment by ayazj111** [comment] 2022-11-13 10:27
1、Chinese Mainland is hard to connect to the test network
2、ECS with static IP address; SnarkOS which file is configured with IP address

**Comment by fwhappy** [comment] 2022-11-14 05:04
2022-11-14T05:02:04.035356Z TRACE Skipping connection request to '159.223.204.96:4133' (tried 72 secs ago)
2022-11-14T05:02:09.390920Z  WARN Skipping an iteration of the prover solution (no connected peers)
2022-11-14T05:02:09.390945Z  WARN Skipping an iteration of the prover solution (no connected peers)
2022-11-14T05:02:09.390964Z  WARN Skipping an iteration of the prover solution (no connected peers)
2022-11-14T05:02:13.035779Z DEBUG Peers: []
2022-11-14T05:02:13.035884Z TRACE Skipping connection request to '159.223.204.96:4133' (tried 81 secs ago)
2022-11-14T05:02:21.986851Z  WARN [PuzzleRequest] There are no reliable peers available yet
2022-11-14T05:02:22.037127Z DEBUG Peers: []
2022-11-14T05:02:22.037247Z TRACE Skipping connection request to '159.223.204.96:4133' (tried 90 secs ago)
2022-11-14T05:02:31.037912Z DEBUG Peers: []
2022-11-14T05:02:31.038021Z TRACE Skipping connection request to '159.223.204.96:4133' (tried 99 secs ago)
2022-11-14T05:02:34.391535Z  WARN Skipping an iteration of the prover solution (no connected peers)
2022-11-14T05:02:34.391564Z  WARN Skipping an iteration of the prover solution (no connected peers)
2022-11-14T05:02:34.391548Z  WARN Skipping an iteration of the prover solution (no connected peers)
2022-11-14T05:02:40.038837Z DEBUG Peers: []
2022-11-14T05:02:40.038976Z TRACE Skipping connection request to '159.223.204.96:4133' (tried 108 secs ago)
2022-11-14T05:02:46.988190Z  WARN [PuzzleRequest] There are no reliable peers available yet
2022-11-14T05:02:49.039896Z DEBUG Peers: []
2022-11-14T05:02:49.039999Z TRACE Skipping connection request to '159.223.204.96:4133' (tried 117 secs ago)


The problem still exists.

**Comment by fwhappy** [comment] 2022-11-14 05:27
Is there a solution for this output in the logs?

2022-11-14T05:25:58.683968Z DEBUG Peers: [159.223.204.96:4133]
2022-11-14T05:25:58.684182Z DEBUG Proving 'CoinbasePuzzle' (Epoch 107, Block 27597, Coinbase Target 5076350, Proof Target 39659)
2022-11-14T05:25:59.417955Z TRACE Prover solution was below the necessary proof target (1 < 39659)
2022-11-14T05:25:59.418091Z DEBUG Proving 'CoinbasePuzzle' (Epoch 107, Block 27597, Coinbase Target 5076350, Proof Target 39659)
2022-11-14T05:26:00.145918Z TRACE Prover solution was below the necessary proof target (6 < 39659)
2022-11-14T05:26:00.146051Z DEBUG Proving 'CoinbasePuzzle' (Epoch 107, Block 27597, Coinbase Target 5076350, Proof Target 39659)
2022-11-14T05:26:00.873172Z TRACE Prover solution was below the necessary proof target (1 < 39659)
2022-11-14T05:26:00.873350Z DEBUG Proving 'CoinbasePuzzle' (Epoch 107, Block 27597, Coinbase Target 5076350, Proof Target 39659)
2022-11-14T05:26:01.779291Z TRACE Prover solution was below the necessary proof target (2 < 39659)
2022-11-14T05:26:01.779409Z DEBUG Proving 'CoinbasePuzzle' (Epoch 107, Block 27597, Coinbase Target 5076350, Proof Target 39659)
2022-11-14T05:26:02.566002Z TRACE Prover solution was below the necessary proof target (1 < 39659)
2022-11-14T05:26:02.566234Z DEBUG Proving 'CoinbasePuzzle' (Epoch 107, Block 27597, Coinbase Target 5076350, Proof Target 39659)
2022-11-14T05:26:03.299930Z TRACE Prover solution was below the necessary proof target (3 < 39659)
2022-11-14T05:26:03.300056Z DEBUG Proving 'CoinbasePuzzle' (Epoch 107, Block 27597, Coinbase Target 5076350, Proof Target 39659)
2022-11-14T05:26:04.298031Z TRACE Prover solution was below the necessary proof target (1 < 39659)
2022-11-14T05:26:04.298151Z DEBUG Proving 'CoinbasePuzzle' (Epoch 107, Block 27597, Coinbase Target 5076350, Proof Target 39659)
2022-11-14T05:26:05.096707Z TRACE Prover solution was below the necessary proof target (86 < 39659)
2022-11-14T05:26:05.096856Z DEBUG Proving 'CoinbasePuzzle' (Epoch 107, Block 27597, Coinbase Target 5076350, Proof Target 39659)
2022-11-14T05:26:05.871203Z TRACE Prover solution was below the necessary proof target (2 < 39659)

**Comment by cktkdgh1219** [comment] 2022-11-14 09:53
@niklaslong 
Now, to connect to the beacon, I entered my private key through the `cargo run --release -- start --nodisplay --dev 0 --beacon ` command to run it, but it seems that the private key is not executed.
 
```
      Private Key APrivateKey-----------------------------------------------------GPWH
      View Key AViewKey---------------------------------------------------------rw
      Address aleo1rhg-----------------------------------------------------------p9px

JSON Web Token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGVvMXJoZ2R1NzdoZ3lxZDN4amo4dWN1M2pqOXIya3J3ejZtbnp5ZDgwZ25jcjVmeGN3bGg1cnN2enA5cHgiLCJpYXQiOjE2Njg0MTkwMTQsImV4cCI6MTk4Mzc3OTAxNH0.ueaOKtnJzqjRrKNveSUAl_CGGb-RUoxevUj97QKL0xI

🪪 Your Aleo address is aleo1rhgd-----------------------------------------p9px.
```

The message appears, but the private key and address are not mine. The value was treated privately, in case you didn't know. Considering that other devices also output the same key value and address, it is considered a sampling key.

 The command `cargo run --release -- start --nodisplay --dev 1 --prover ` runs normally using my private key, but the beacon does not run, so the normal prover command is connected to 127.0.0.1 4130 this doesn't work

Any solution?

**Comment by 1ukech3n** [comment] 2022-11-15 06:20
+1, I got similar issues with below message on Ubuntu 18.04 with `./run-prover.sh`

```
2022-11-15T06:17:52.309463Z TRACE Skipping connection request to '167.71.219.176:4133' (tried 144 secs ago)
2022-11-15T06:18:01.310958Z DEBUG Peers: []
2022-11-15T06:18:01.311031Z TRACE Skipping connection request to '167.71.219.176:4133' (tried 153 secs ago)
2022-11-15T06:18:03.540903Z TRACE Received 'ChallengeRequest-B' from '167.71.219.176:4133'
2022-11-15T06:18:03.540928Z TRACE Sending 'ChallengeResponse-B' to '167.71.219.176:4133'
2022-11-15T06:18:04.541606Z TRACE Received 'Disconnect-A' from '167.71.219.176:4133'
2022-11-15T06:18:04.541665Z TRACE Peer 167.71.219.176:4133 disconnected for the following reason: Disconnect { reason: YourPortIsClosed(4133) }
2022-11-15T06:18:09.190960Z  WARN [PuzzleRequest] There are no reliable peers available yet
2022-11-15T06:18:10.312019Z DEBUG Peers: []
2022-11-15T06:18:10.312110Z TRACE Skipping connection request to '167.71.219.176:4133' (tried 162 secs ago)
2022-11-15T06:18:10.441232Z  WARN Skipping an iteration of the prover solution (no connected peers)
2022-11-15T06:18:10.444340Z  WARN Skipping an iteration of the prover solution (no connected peers)
2022-11-15T06:18:10.444362Z  WARN Skipping an iteration of the prover solution (no connected peers)
2022-11-15T06:18:19.313486Z DEBUG Peers: []
2022-11-15T06:18:19.313573Z TRACE Skipping connection request to '167.71.219.176:4133' (tried 171 secs ago)
2022-11-15T06:18:28.315010Z DEBUG Peers: []
```

**Comment by Alarical** [comment] 2022-11-15 06:32
I had the same problem

**Comment by myDawn** [comment] 2022-11-15 10:37
I had the same problem
2022-11-15T10:36:53.053088Z TRACE Skipping connection request to '134.122.95.106:4133' (tried 108 secs ago)
2022-11-15T10:37:02.054677Z DEBUG Peers: []
2022-11-15T10:37:02.054758Z TRACE Skipping connection request to '134.122.95.106:4133' (tried 117 secs ago)
2022-11-15T10:37:11.055724Z DEBUG Peers: []
2022-11-15T10:37:11.055912Z TRACE Skipping connection request to '134.122.95.106:4133' (tried 126 secs ago)
2022-11-15T10:37:11.598778Z  WARN Skipping an iteration of the prover solution (no connected peers)
2022-11-15T10:37:11.598791Z  WARN Skipping an iteration of the prover solution (no connected peers)
2022-11-15T10:37:11.598808Z  WARN Skipping an iteration of the prover solution (no connected peers)
2022-11-15T10:37:17.998485Z  WARN [PuzzleRequest] There are no reliable peers available yet
2022-11-15T10:37:20.056762Z DEBUG Peers: []
2022-11-15T10:37:20.056860Z TRACE Skipping connection request to '134.122.95.106:4133' (tried 135 secs ago)
2022-11-15T10:37:29.058016Z DEBUG Peers: []
2022-11-15T10:37:29.058096Z TRACE Skipping connection request to '134.122.95.106:4133' (tried 144 secs ago)

**Comment by humantraffic** [comment] 2022-11-15 13:02
same problems

**Comment by gub176** [comment] 2022-11-15 14:09
2022-11-15T14:06:34.697864Z DEBUG Peers: []
2022-11-15T14:06:34.698002Z TRACE Skipping connection request to '164.92.111.59:4133' (tried 144 secs ago)
2022-11-15T14:06:36.545503Z  WARN [PuzzleRequest] There are no reliable peers available yet
2022-11-15T14:06:37.981291Z  WARN Skipping an iteration of the prover solution (no connected peers)
2022-11-15T14:06:37.981315Z  WARN Skipping an iteration of the prover solution (no connected peers)
2022-11-15T14:06:37.981322Z  WARN Skipping an iteration of the prover solution (no connected peers)
2022-11-15T14:06:43.698428Z DEBUG Peers: []
2022-11-15T14:06:43.698564Z TRACE Skipping connection request to '164.92.111.59:4133' (tried 153 secs ago)
2022-11-15T14:06:52.699367Z DEBUG Peers: []
2022-11-15T14:06:52.699500Z TRACE Skipping connection request to '164.92.111.59:4133' (tried 162 secs ago)
2022-11-15T14:07:01.546355Z  WARN [PuzzleRequest] There are no reliable peers available yet
2022-11-15T14:07:01.700761Z DEBUG Peers: []
2022-11-15T14:07:01.700901Z TRACE Skipping connection request to '164.92.111.59:4133' (tried 171 secs ago)
2022-11-15T14:07:02.982689Z  WARN Skipping an iteration of the prover solution (no connected peers)
2022-11-15T14:07:02.982713Z  WARN Skipping an iteration of the prover solution (no connected peers)
2022-11-15T14:07:02.982721Z  WARN Skipping an iteration of the prover solution (no connected peers)
2022-11-15T14:07:10.701909Z DEBUG Peers: []
2022-11-15T14:07:10.702040Z DEBUG Connecting to '164.92.111.59:4133'...
2022-11-15T14:07:11.703348Z ERROR Unable to reach '164.92.111.59:4133': 'Elapsed(())'
2022-11-15T14:07:19.703147Z DEBUG Peers: []
2022-11-15T14:07:19.703278Z TRACE Skipping connection request to '164.92.111.59:4133' (tried 9 secs ago)
2022-11-15T14:07:26.547782Z  WARN [PuzzleRequest] There are no reliable peers available yet
2022-11-15T14:07:27.983407Z  WARN Skipping an iteration of the prover solution (no connected peers)
2022-11-15T14:07:27.983431Z  WARN Skipping an iteration of the prover solution (no connected peers)
2022-11-15T14:07:27.983438Z  WARN Skipping an iteration of the prover solution (no connected peers)
2022-11-15T14:07:28.704504Z DEBUG Peers: []
2022-11-15T14:07:28.704633Z TRACE Skipping connection request to '164.92.111.59:4133' (tried 18 secs ago)
2022-11-15T14:07:37.705499Z DEBUG Peers: []
2022-11-15T14:07:37.705657Z TRACE Skipping connection request to '164.92.111.59:4133' (tried 27 secs ago)
2022-11-15T14:07:46.706371Z DEBUG Peers: []
2022-11-15T14:07:46.706505Z TRACE Skipping connection request to '164.92.111.59:4133' (tried 36 secs ago)
2022-11-15T14:07:51.548992Z  WARN [PuzzleRequest] There are no reliable peers available yet
2022-11-15T14:07:52.984799Z  WARN Skipping an iteration of the prover solution (no connected peers)
2022-11-15T14:07:52.984824Z  WARN Skipping an iteration of the prover solution (no connected peers)
2022-11-15T14:07:52.984831Z  WARN Skipping an iteration of the prover solution (no connected peers)
2022-11-15T14:07:55.707861Z DEBUG Peers: []
2022-11-15T14:07:55.707997Z TRACE Skipping connection request to '164.92.111.59:4133' (tried 45 secs ago)
2022-11-15T14:08:04.708984Z DEBUG Peers: []
2022-11-15T14:08:04.709116Z TRACE Skipping connection request to '164.92.111.59:4133' (tried 54 secs ago)
2022-11-15T14:08:13.709963Z DEBUG Peers: []
2022-11-15T14:08:13.710097Z TRACE Skipping connection request to '164.92.111.59:4133' (tried 63 secs ago)
2022-11-15T14:08:16.550446Z  WARN [PuzzleRequest] There are no reliable peers available yet
2022-11-15T14:08:17.985174Z  WARN Skipping an iteration of the prover solution (no connected peers)
2022-11-15T14:08:17.985198Z  WARN Skipping an iteration of the prover solution (no connected peers)
2022-11-15T14:08:17.985206Z  WARN Skipping an iteration of the prover solution (no connected peers)
2022-11-15T14:08:22.710489Z DEBUG Peers: []
2022-11-15T14:08:22.710620Z TRACE Skipping connection request to '164.92.111.59:4133' (tried 72 secs ago)
2022-11-15T14:08:31.711501Z DEBUG Peers: []
2022-11-15T14:08:31.711630Z TRACE Skipping connection request to '164.92.111.59:4133' (tried 81 secs ago)
2022-11-15T14:08:40.712300Z DEBUG Peers: []
2022-11-15T14:08:40.712432Z TRACE Skipping connection request to '164.92.111.59:4133' (tried 90 secs ago)
2022-11-15T14:08:41.551577Z  WARN [PuzzleRequest] There are no reliable peers available yet
2022-11-15T14:08:42.986453Z  WARN Skipping an iteration of the prover solution (no connected peers)
2022-11-15T14:08:42.986477Z  WARN Skipping an iteration of the prover solution (no connected peers)
2022-11-15T14:08:42.986485Z  WARN Skipping an iteration of the prover solution (no connected peers)

**Comment by gub176** [comment] 2022-11-15 14:09
same problem not connection ...

**Comment by zvolin** [comment] 2022-11-15 16:34
@1ukech3n Your case is likely different, it seems that your connection was dropped as you have port 4133/tcp closed on your router. Please check [FAQ](https://github.com/AleoHQ/snarkOS#2-my-node-is-unable-to-connect-to-peers-on-the-network).
From your log:
> TRACE Peer 167.71.219.176:4133 disconnected for the following reason: Disconnect { reason: YourPortIsClosed(4133) }

@fwhappy Your issue was discussed there #2056.

For all others, as  @niklaslong said, most likely you cannot connect because the beacon peer limits being reached and it therefore being unable to accept new connections.
Have any of you actually managed to get through by retrying after some time?

**Comment by sedasdas** [comment] 2022-11-15 17:14
![image](https://user-images.githubusercontent.com/13110234/201983691-177b4cd6-7fb6-4d9a-b9bb-41ec050fbe53.png)

**Comment by sedasdas** [comment] 2022-11-15 17:16
Again, sometimes it works, sometimes it stays stuck

**Comment by kallivad** [comment] 2022-11-16 05:10
The same for me, sometimes its get connected, sometimes not. It was crashed 2 days ago, now simple loosing the connection to peers:

2022-11-16T04:43:07.065780Z DEBUG Proving 'CoinbasePuzzle' (Epoch 152, Block 39100, Coinbase Target 10063422, Proof Target 78621)
2022-11-16T04:43:07.066421Z DEBUG Proving 'CoinbasePuzzle' (Epoch 152, Block 39100, Coinbase Target 10063422, Proof Target 78621)
2022-11-16T04:43:07.069069Z TRACE Prover solution was below the necessary proof target (2 < 78621)
2022-11-16T04:43:07.069137Z  WARN Skipping an iteration of the prover solution (no connected peers)
2022-11-16T04:43:07.090902Z TRACE Prover solution was below the necessary proof target (16 < 78621)
2022-11-16T04:43:07.133789Z TRACE Prover solution was below the necessary proof target (2 < 78621)
2022-11-16T04:43:07.133867Z TRACE Prover solution was below the necessary proof target (1 < 78621)
2022-11-16T04:43:07.154846Z TRACE Prover solution was below the necessary proof target (1 < 78621)
2022-11-16T04:43:07.197119Z TRACE Prover solution was below the necessary proof target (1 < 78621)
2022-11-16T04:43:07.200163Z TRACE Prover solution was below the necessary proof target (1 < 78621)
2022-11-16T04:43:07.226332Z TRACE Prover solution was below the necessary proof target (2 < 78621)
2022-11-16T04:43:13.857550Z DEBUG Peers: []
2022-11-16T04:43:13.857581Z TRACE Attempting connection to '164.92.111.59:4133'...
2022-11-16T04:43:13.857641Z DEBUG Connecting to '164.92.111.59:4133'...
2022-11-16T04:43:13.857768Z TRACE Skipping connection request to '164.92.111.59:4133' (tried 0 secs ago)
2022-11-16T04:43:14.858964Z ERROR Unable to reach '164.92.111.59:4133': 'Elapsed(())'
2022-11-16T04:43:20.623343Z  WARN Skipping an iteration of the prover solution (no connected peers)
2022-11-16T04:43:20.623384Z  WARN Skipping an iteration of the prover solution (no connected peers)
2022-11-16T04:43:22.858859Z DEBUG Peers: []

**Comment by makertronic** [comment] 2022-11-18 00:42
i got the same error. 
i just restarted 2 or 3 times until its ok.

**Comment by Dang-dang** [comment] 2022-11-18 18:44
> ![image](https://user-images.githubusercontent.com/13110234/201500293-2729d71c-62b8-4d23-bbd7-035cbcc1f971.png) This happens after a while, later normal, and so on

I met the same problem, Can you tell me how you solve it?

**Comment by AREZA13** [comment] 2022-11-28 16:40
same problem - it works some time then cant connect to peers. 


2022-11-28T02:38:52.983316Z TRACE Proving 'CoinbasePuzzle' [2m(Epoch 421, Coinbase Target 31128192, Proof Target 243190)[0m
2022-11-28T02:38:52.983320Z TRACE Proving 'CoinbasePuzzle' [2m(Epoch 421, Coinbase Target 31128192, Proof Target 243190)[0m
2022-11-28T02:38:53.032852Z  WARN Skipping an iteration of the coinbase puzzle (latest block is stale)
2022-11-28T02:38:53.032877Z  WARN Skipping an iteration of the coinbase puzzle (latest block is stale)
2022-11-28T02:38:53.032940Z  WARN Skipping an iteration of the coinbase puzzle (latest block is stale)
2022-11-28T02:38:53.077277Z  WARN Skipping an iteration of the coinbase puzzle (latest block is stale)
2022-11-28T02:38:53.077277Z  WARN Skipping an iteration of the coinbase puzzle (latest block is stale)
2022-11-28T02:38:53.077282Z  WARN Skipping an iteration of the coinbase puzzle (latest block is stale)
2022-11-28T02:38:53.276592Z TRACE Sending 'Ping' to '125.212.196.100:4133'
2022-11-28T02:38:53.553034Z TRACE Received 'Ping' from '125.212.196.100:4133'
2022-11-28T02:38:53.553046Z TRACE Sending 'Pong' to '125.212.196.100:4133'
2022-11-28T02:38:53.836958Z TRACE Received 'Pong' from '125.212.196.100:4133'
2022-11-28T02:38:53.886596Z DEBUG Connecting to 138.197.190.94:4133...
2022-11-28T02:38:53.946647Z  WARN Dropping connection request from '138.197.190.94:4133' (restricted)
2022-11-28T02:38:56.396608Z DEBUG Connecting to 138.197.190.94:4133...
2022-11-28T02:38:56.466702Z  WARN Dropping connection request from '138.197.190.94:4133' (restricted)
2022-11-28T02:38:57.696597Z DEBUG Connected to 2 peers: [38.242.197.248:4133, 125.212.196.100:4133]
2022-11-28T02:38:57.696631Z DEBUG Connecting to 138.68.103.139:4133...
2022-11-28T02:38:57.753668Z  WARN Dropping connection request from '138.68.103.139:4133' (restricted)
2022-11-28T02:38:58.906608Z DEBUG Connecting to 159.223.204.96:4133...
2022-11-28T02:38:59.112673Z  WARN Dropping connection request from '159.223.204.96:4133' (restricted)
2022-11-28T02:39:01.416614Z DEBUG Connecting to 161.35.24.55:4133...
2022-11-28T02:39:01.476668Z  WARN Dropping connection request from '161.35.24.55:4133' (restricted)
2022-11-28T02:39:03.926615Z DEBUG Connecting to 157.245.205.209:4133...


Restarts dont help same as reboot

**Comment by howardwu** [comment] 2022-12-04 19:54
The current requirement is for the prover to connect to validators (no need for beacons).

As of the `V4` fork this week, anyone is now able to run a validator. You can then target your provers to connect to your validator with the `--connect "{your_validator_IP:port}"` flag.

I will preemptively close this PR as the issue has been addressed in `V4`.

**Closed as completed by howardwu** 2022-12-04 19:54 UTC
Labels: bug, network, unconfirmed, testnet3
