### ISSUE TITLE
Compilation Failure in snarkOS-node-consensus v2.2.7 due to Deprecated Methods and Type Mismatch

### ISSUE THREAD

**Issue by SeloSlav** [AleoHQ/snarkOS#3057] opened 2024-02-04 16:26 UTC
### Description
During the compilation of snarkOS-node-consensus v2.2.7, multiple warnings and an error were encountered related to deprecated methods and mismatched types.

### Severity
The issue seems to block the compilation process, indicating a critical severity level as it halts further development or usage of the software until resolved.

### Affected
This affects the `snarkOS-node-consensus` module, particularly the compilation process which is critical for development and deployment.

## Steps to Reproduce
1. Compile snarkOS-node-consensus v2.2.7 using Rust.
2. Observe the warnings about deprecated `indexmap::IndexMap::remove` methods.
3. Encounter the error `E0308: mismatched types` in `node/rest/src/lib.rs` at line `115:54`.

### Error Messages and Stack Traces
- Warnings for deprecated `indexmap::IndexMap::remove` method suggest using `swap_remove` for explicit behavior.
- Compilation error `E0308` in `node/rest/src/lib.rs` indicates an expected `Body` type but found a `String` type instead.

## Expected Behavior
The compilation process should complete without errors or warnings, allowing the software to build successfully.

## Your Environment
- snarkOS Version: v2.2.7
- Rust Version: rustc 1.69.0 (84c898d65 2023-04-16)
- Computer OS: Windows 10 Version 22H2 (OS Build 10945.3930)

**Comment by ljedrz** [comment] 2024-02-04 20:26
Both issues are caused by using the build script (**not** plain compilation) and already have pending fixes (or rather adjustments to dependency updates), as does the build script.

**Comment by SeloSlav** [comment] 2024-02-05 01:30
Would you advise doing a clean install with a manual compilation? I can't
get the prover node to run.

**Comment by ljedrz** [comment] 2024-02-05 08:15
Yes, a clean install followed by either manual compilation or adding the `--locked` param to the `cargo install` in the build script will solve the issue.

**Comment by ljedrz** [comment] 2024-02-05 11:00
Fixed by the second commit in https://github.com/AleoHQ/snarkOS/pull/3050.

**Comment by nesg-9424** [comment] 2024-02-06 00:06
> Both issues are caused by using the build script (**not** plain compilation) and already have pending fixes (or rather adjustments to dependency updates), as does the build script.

Is the fix pushed already?

**Comment by ljedrz** [comment] 2024-02-06 10:40
Not yet, but it's quite simple to apply it locally (either use `cargo install` with `--locked` or build manually via `cargo build --release`) if you'd like to use it already.

**Comment by gagermaniac** [comment] 2024-02-06 15:43
> Not yet, but it's quite simple to apply it locally (either use `cargo install` with `--locked` or build manually via `cargo build --release`) if you'd like to use it already.

i still got above issue when running run-prover.sh, first cargo install works fine

**Comment by oliveirarodrigo22** [comment] 2024-02-07 19:02
o faucet não tá funcionando.

**Comment by nesg-9424** [comment] 2024-02-07 21:00
> > Not yet, but it's quite simple to apply it locally (either use `cargo install` with `--locked` or build manually via `cargo build --release`) if you'd like to use it already.
> 
> i still got above issue when running run-prover.sh, first cargo install works fine

I got the same issue. ./run-prover.sh still having issue.

**Comment by Taito-1009** [comment] 2024-02-07 21:13
Hi,

I'm encountering the same error when trying to build. I'm not an expert and I'm followigin some guidelines to run my own Aleo node. I'm doing this : "git clone https://github.com/AleoHQ/snarkOS.git --depth 1" and then "./build_ubuntu.sh./". How can I clone and download the snarkOS version with the bug fix ? I'm not mastering git command unfortunalety - thx

**Comment by Jouzep** [comment] 2024-02-07 21:18
Go to the fixed branch
```
git checkout 8babab849efea826d8366e8d7f4d2ec72b1c059a 
```
Clean and re build
```
cargo clean
./build_ubuntu.sh
```
and then do what you want

**Comment by Taito-1009** [comment] 2024-02-07 21:33
Thanks Jouzep. Do I still need to do this "git clone https://github.com/AleoHQ/snarkOS.git" before doing "git checkout 8babab849efea826d8366e8d7f4d2ec72b1c059a" ? I'm working with putty to access my VPS.

**Comment by SeloSlav** [comment] 2024-02-07 21:50
> Go to the fixed branch
> 
> ```
> git checkout 8babab849efea826d8366e8d7f4d2ec72b1c059a 
> ```
> 
> Clean and re build
> 
> ```
> cargo clean
> ./build_ubuntu.sh
> ```
> 
> and then do what you want

I keep getting ``fatal: reference is not a tree:`` when trying to checkout the branch rom the snarkOS folder... What should I do here?

**Comment by Jouzep** [comment] 2024-02-08 08:43
the changes have been merged, just reclone the repo, it should work fine now

**Comment by ljedrz** [comment] 2024-02-08 09:14
Fixed by https://github.com/AleoHQ/snarkOS/pull/3050.

**Closed as completed by ljedrz** 2024-02-08 09:14 UTC
Labels: bug
