### ISSUE TITLE
[Bug]  compiling snarkvm-ledger-store fails with error snarkvm-ledger-store

### ISSUE THREAD

**Issue by ranjithrajaram** [AleoHQ/snarkOS#3023] opened 2024-01-22 08:27 UTC
## 🐛 Bug Report

Executing ./build_ubuntu.sh fails with the following error. I did not find a similar report, so filing a new one

```
error[E0308]: mismatched types
   --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/snarkvm-ledger-store-0.16.11/src/helpers/rocksdb/internal/mod.rs:113:69
    |
113 |                 let primary = aleo_std::aleo_ledger_dir(network_id, dev);
    |                               -------------------------             ^^^ expected `StorageMode`, found `Option<u16>`
    |                               |
    |                               arguments to this function are incorrect
    |
    = note: expected enum `StorageMode`
               found enum `std::option::Option<u16>`
note: function defined here
   --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aleo-std-storage-0.1.7/src/lib.rs:89:8
    |
89  | pub fn aleo_ledger_dir(network: u16, mode: StorageMode) -> PathBuf {
    |        ^^^^^^^^^^^^^^^
help: call `Into::into` on this expression to convert `std::option::Option<u16>` into `StorageMode`
    |
113 |                 let primary = aleo_std::aleo_ledger_dir(network_id, dev.into());
    |                                                                        +++++++
```

## Steps to Reproduce

git clone https://github.com/AleoHQ/snarkOS.git --depth 1
cd snarkOS
./build_ubuntu.sh

## Expected Behavior

Compilation should work successfully

## Your Environment

-  v2.2.5 
-    rustc 1.75.0
-  Ubuntu 22.04.3 LTS

**Comment by ljedrz** [comment] 2024-01-22 16:43
It's due to `aleo-std` just having received some breaking changes and a version bump. I'm pretty sure snarkOS will be adjusted to it shortly, but in the meantime you can fix it locally by tweaking the contents of `node/Cargo.toml` and `cli/Cargo.toml` as follows: just find
```
[dependencies.aleo-std]
version = "0.1.18"
```
and change it to
```
[dependencies.aleo-std]
version = "=0.1.18"
```

**Comment by nomadnft69** [comment] 2024-01-23 02:38
> It's due to `aleo-std` just having received some breaking changes and a version bump. I'm pretty sure snarkOS will be adjusted to it shortly, but in the meantime you can fix it locally by tweaking the contents of `node/Cargo.toml` and `cli/Cargo.toml` as follows: just find
> 
> ```
> [dependencies.aleo-std]
> version = "0.1.18"
> ```
> 
> and change it to
> 
> ```
> [dependencies.aleo-std]
> version = "=0.1.18"
> ```

your saying change it to the same thing?? think you forgot to copy and paste the right info thnks

**Comment by ljedrz** [comment] 2024-01-23 03:43
No; note the added equals sign (`=`).

**Comment by joske** [comment] 2024-01-23 08:27
The PR above updates the code to the API change, but @ljedrz change may be safer until @howardwu can look at the PR.

**Comment by mooser1** [comment] 2024-01-23 10:38
Executing ./build_ubuntu.sh after doing this fix fails with the following error:

Compiling aleo-std v0.1.18
error[E0432]: unresolved imports `aleo_std_storage::aleo_operator_dir`, `aleo_st                                                                                                                                   d_storage::aleo_prover_dir`
  --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aleo-std-0.1.18                                                                                                                                   /src/lib.rs:21:55
   |
21 | ..._ledger_dir, aleo_operator_dir, aleo_prover_dir};
   |                 ^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^
   |                 |                  |
   |                 |                  no `aleo_prover_dir` in the root
   |                 |                  help: a similar name exists in the modul                                                                                                                                   e: `aleo_ledger_dir`
   |                 no `aleo_operator_dir` in the root

error[E0432]: unresolved imports `aleo_std_storage::aleo_operator_dir`, `aleo_st                                                                                                                                   d_storage::aleo_prover_dir`
  --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aleo-std-0.1.18                                                                                                                                   /src/lib.rs:28:59
   |
28 | ..._ledger_dir, aleo_operator_dir, aleo_prover_dir};
   |                 ^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^
   |                 |                  |
   |                 |                  no `aleo_prover_dir` in the root
   |                 |                  help: a similar name exists in the modul                                                                                                                                   e: `aleo_ledger_dir`
   |                 no `aleo_operator_dir` in the root
   |
   = help: consider importing this unresolved item through its public re-export                                                                                                                                    instead:
           crate::aleo_operator_dir
   = help: consider importing this unresolved item through its public re-export                                                                                                                                    instead:
           crate::aleo_prover_dir

For more information about this error, try `rustc --explain E0432`.
error: could not compile `aleo-std` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `snarkos v2.2.7 (/root/snarkOS)`, intermediate artifact                                                                                                                                   s can be found at `/root/snarkOS/target`.
To reuse those artifacts with a future compilation, set the environment variable                                                                                                                                    `CARGO_TARGET_DIR` to that path.

**Comment by ljedrz** [comment] 2024-01-23 10:41
Ah, I didn't notice that the script was used to build; my workaround will work only with a local `cargo build`, not with `cargo install` that's used in the script.

**Comment by ronming1303** [comment] 2024-01-25 00:01
> Executing ./build_ubuntu.sh after doing this fix fails with the following error:
> 
> Compiling aleo-std v0.1.18 error[E0432]: unresolved imports `aleo_std_storage::aleo_operator_dir`, `aleo_st d_storage::aleo_prover_dir` --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aleo-std-0.1.18 /src/lib.rs:21:55 | 21 | ..._ledger_dir, aleo_operator_dir, aleo_prover_dir}; | ^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^ | | | | | no `aleo_prover_dir` in the root | | help: a similar name exists in the modul e: `aleo_ledger_dir` | no `aleo_operator_dir` in the root
> 
> error[E0432]: unresolved imports `aleo_std_storage::aleo_operator_dir`, `aleo_st d_storage::aleo_prover_dir` --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aleo-std-0.1.18 /src/lib.rs:28:59 | 28 | ..._ledger_dir, aleo_operator_dir, aleo_prover_dir}; | ^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^ | | | | | no `aleo_prover_dir` in the root | | help: a similar name exists in the modul e: `aleo_ledger_dir` | no `aleo_operator_dir` in the root | = help: consider importing this unresolved item through its public re-export instead: crate::aleo_operator_dir = help: consider importing this unresolved item through its public re-export instead: crate::aleo_prover_dir
> 
> For more information about this error, try `rustc --explain E0432`. error: could not compile `aleo-std` (lib) due to 2 previous errors warning: build failed, waiting for other jobs to finish... error: failed to compile `snarkos v2.2.7 (/root/snarkOS)`, intermediate artifact s can be found at `/root/snarkOS/target`. To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

I also have a same issue : (

**Comment by joske** [comment] 2024-01-25 07:29
The fix is in the linked PR

**Comment by ranjithrajaram** [comment] 2024-01-25 11:21
The PR fixes the problem(manual application of the patch)

**Comment by Zack-Xb** [comment] 2024-01-25 12:32
@joske Thanks for the fix.

**Comment by jkdi** [comment] 2024-01-27 11:24
Compiling snarkos v2.2.7 (/root/snarkOS)
error[E0432]: unresolved imports `aleo_std_storage::aleo_operator_dir`, `aleo_std_storage::aleo_prover_dir`
  --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aleo-std-0.1.18/src/lib.rs:21:55
   |
21 | pub use aleo_std_storage::{aleo_dir, aleo_ledger_dir, aleo_operator_dir, aleo_prover_dir};
   |                                                       ^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^
   |                                                       |                  |
   |                                                       |                  no `aleo_prover_dir` in the root
   |                                                       |                  help: a similar name exists in the module: `aleo_ledger_dir`
   |                                                       no `aleo_operator_dir` in the root

error[E0432]: unresolved imports `aleo_std_storage::aleo_operator_dir`, `aleo_std_storage::aleo_prover_dir`
  --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aleo-std-0.1.18/src/lib.rs:28:59
   |
28 |     pub use aleo_std_storage::{aleo_dir, aleo_ledger_dir, aleo_operator_dir, aleo_prover_dir};
   |                                                           ^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^^^^
   |                                                           |                  |
   |                                                           |                  no `aleo_prover_dir` in the root
   |                                                           |                  help: a similar name exists in the module: `aleo_ledger_dir`
   |                                                           no `aleo_operator_dir` in the root
   |
   = help: consider importing this unresolved item through its public re-export instead:
           crate::aleo_operator_dir
   = help: consider importing this unresolved item through its public re-export instead:
           crate::aleo_prover_dir

For more information about this error, try `rustc --explain E0432`.
error: could not compile `aleo-std` (lib) due to 2 previous errors
error: failed to compile `snarkos v2.2.7 (/root/snarkOS)`, intermediate artifacts can be found at `/root/snarkOS/target`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

**Comment by jkdi** [comment] 2024-01-27 11:25
fix with version = "=0.1.18" dont work

**Comment by farreledwin** [comment] 2024-01-28 09:53
yeah me too with "=0.1.18" dont work

**Comment by joske** [comment] 2024-01-29 08:43
Fixed.

**Closed as completed by joske** 2024-01-29 08:43 UTC
Labels: bug

**Comment by osirisss11** [comment] 2024-01-30 01:13
what is the fix? using manual build? cant be fixed on github?

**Comment by joske** [comment] 2024-01-30 08:04
@osirisss11  just update your branch and rebuild.

**Comment by jkdi** [comment] 2024-01-30 08:55
why does nobody test the building process??? in ubuntu 22.04. are now a lot of new warnings!

**Comment by jkdi** [comment] 2024-01-30 08:55
warning: use of deprecated method `indexmap::IndexSet::<T, S>::remove`: `remove` disrupts the set order -- use `swap_remove` or `shift_remove` for explicit behavior.
   --> node/router/src/helpers/cache.rs:137:72
    |
137 |         if let Some(requests) = map_write.get_mut(&peer_ip) { requests.remove(request) } else { false }
    |                                                                        ^^^^^^
    |
    = note: `#[warn(deprecated)]` on by default

warning: use of deprecated method `indexmap::IndexMap::<K, V, S>::remove`: `remove` disrupts the map order -- use `swap_remove` or `shift_remove` for explicit behavior.
   --> node/router/src/helpers/cache.rs:230:23
    |
230 |             map_write.remove(&key);
    |                       ^^^^^^

warning: use of deprecated method `indexmap::IndexMap::<K, V, S>::remove`: `remove` disrupts the map order -- use `swap_remove` or `shift_remove` for explicit behavior.
  --> node/router/src/helpers/resolver.rs:58:61
   |
58 |         if let Some(peer_addr) = self.from_listener.write().remove(listener_ip) {
   |                                                             ^^^^^^

warning: use of deprecated method `indexmap::IndexMap::<K, V, S>::remove`: `remove` disrupts the map order -- use `swap_remove` or `shift_remove` for explicit behavior.
  --> node/router/src/helpers/resolver.rs:59:38
   |
59 |             self.to_listener.write().remove(&peer_addr);
   |                                      ^^^^^^

warning: use of deprecated method `indexmap::IndexSet::<T, S>::remove`: `remove` disrupts the set order -- use `swap_remove` or `shift_remove` for explicit behavior.
   --> node/router/src/lib.rs:405:38
    |
405 |         self.candidate_peers.write().remove(&peer_ip);
    |                                      ^^^^^^

warning: use of deprecated method `indexmap::IndexMap::<K, V, S>::remove`: `remove` disrupts the map order -- use `swap_remove` or `shift_remove` for explicit behavior.
   --> node/router/src/lib.rs:407:39
    |
407 |         self.restricted_peers.write().remove(&peer_ip);
    |                                       ^^^^^^

warning: use of deprecated method `indexmap::IndexSet::<T, S>::remove`: `remove` disrupts the set order -- use `swap_remove` or `shift_remove` for explicit behavior.
   --> node/router/src/lib.rs:437:38
    |
437 |         self.candidate_peers.write().remove(&peer_ip);
    |                                      ^^^^^^

warning: use of deprecated method `indexmap::IndexMap::<K, V, S>::remove`: `remove` disrupts the map order -- use `swap_remove` or `shift_remove` for explicit behavior.
   --> node/router/src/lib.rs:468:38
    |
468 |         self.connected_peers.write().remove(&peer_ip);
    |                                      ^^^^^^

warning: use of deprecated method `indexmap::IndexSet::<T, S>::remove`: `remove` disrupts the set order -- use `swap_remove` or `shift_remove` for explicit behavior.
   --> node/router/src/lib.rs:484:38
    |
484 |         self.candidate_peers.write().remove(&peer_ip);
    |                                      ^^^^^^

**Comment by ljedrz** [comment] 2024-01-30 09:10
@jkdi these are caused by some very fresh deprecations from a dependency; I don't know how you're building snarkOS, but that dependency has not been updated in the lockfile yet.

**Comment by joske** [comment] 2024-01-30 09:11
@jkdi I don't have any warnings with current `testnet3` branch.

**Comment by howardwu** [comment] 2024-01-30 19:05
@jhdi The warnings are not breakages, please understand the differences before filing a complaint.

@ljedrz can you evaluate each of the `remove` cases and decide whether `shift` or `swap` is necessary?

**Comment by osirisss11** [comment] 2024-01-31 21:28
> @osirisss11 just update your branch and rebuild.

how exactly do i update branch? whats the command for that

**Comment by joske** [comment] 2024-01-31 22:07
@osirisss11 
`git pull`

**Comment by WeirdoPunk** [comment] 2024-02-21 11:18
> @osirisss11 `git pull`

still use the minnet branch?
