### ISSUE TITLE
[Bug] unstable library feature in `snarkvm-algorithms`

### ISSUE THREAD

**Issue by hryksbt** [AleoHQ/snarkOS#2021] opened 2022-11-06 18:56 UTC
## 🐛 Bug Report

When I execute run-client.sh, I face below error.

`error[E0658]: use of unstable library feature 'bool_to_option'
  --> /root/.cargo/git/checkouts/snarkvm-f1160780ffe17de8/1f0f2c9/console/algorithms/src/blake2xs/hash_to_curve.rs:54:28
   |
54 |             (!g.is_zero()).then_some(g)
   |                            ^^^^^^^^^
   |
   = note: see issue #80967 <https://github.com/rust-lang/rust/issues/80967> for more information

For more information about this error, try `rustc --explain E0658`.
error: could not compile `snarkvm-console-algorithms` due to previous error
warning: build failed, waiting for other jobs to finish...
error[E0658]: use of unstable library feature 'bool_to_option'
  --> /root/.cargo/git/checkouts/snarkvm-f1160780ffe17de8/1f0f2c9/algorithms/src/snark/marlin/ahp/ahp.rs:53:16
   |
53 |         MM::ZK.then_some(1)
   |                ^^^^^^^^^
   |
   = note: see issue #80967 <https://github.com/rust-lang/rust/issues/80967> for more information

error[E0658]: use of unstable library feature 'bool_to_option'
   --> /root/.cargo/git/checkouts/snarkvm-f1160780ffe17de8/1f0f2c9/algorithms/src/snark/marlin/ahp/prover/round_functions/first.rs:116:43
    |
116 |         state.mz_poly_randomizer = MM::ZK.then_some(r_b_s);
    |                                           ^^^^^^^^^
    |
    = note: see issue #80967 <https://github.com/rust-lang/rust/issues/80967> for more information

error[E0658]: use of unstable library feature 'bool_to_option'
   --> /root/.cargo/git/checkouts/snarkvm-f1160780ffe17de8/1f0f2c9/algorithms/src/snark/marlin/data_structures/proof.rs:176:78
    |
176 |         let z_b_evals = map.iter().filter_map(|(k, v)| k.starts_with("z_b_").then_some(*v)).collect::<Vec<_>>();
    |                                                                              ^^^^^^^^^
    |
    = note: see issue #80967 <https://github.com/rust-lang/rust/issues/80967> for more information

error: could not compile `snarkvm-algorithms` due to 3 previous errors
`

## Steps to Reproduce

1. Step 1... Following this installation. - https://github.com/AleoHQ/snarkOS#22-installation
2. Step 2... Execute ./run-client.sh in snarkOS directory.
3. Step 3... Facing above error. Then this shell script can't run.

## Expected Behavior

Staring phase 1 mining process.

## Your Environment

- snarkOS Version = latest
- Rust Version = latest
- Ubuntu 22.04.1
- Intel Core i7 11800H, 16GB RAM, RTX3080 laptop

**Comment by niklaslong** [comment] 2022-11-08 08:39
There have been many changes to both snarkOS and snarkVM recently, could you pull the latest commits and try again?

**Comment by hryksbt** [comment] 2022-11-08 09:24
Thank you, 
I did git pull. But same result.
I think you should check error message then fix issue.
Regards,

**Comment by niklaslong** [comment] 2022-11-08 09:32
I haven't been able to reproduce so far, as a sanity check, you are on commit `cf9f4a488802655235b06f0d7d38903c7af5bd5e`?

**Comment by hryksbt** [comment] 2022-11-08 09:59
I got the reason.
run-client.sh cannot work with sudo command.
I need to be a root user. Then it works.
If this is unexpected, please consider to update.

Thank you,

**Comment by niklaslong** [comment] 2022-11-08 10:15
Glad you got it working. `run-client.sh` works fine for me with `sudo`. Closing this issue as it seems to be resolved.

**Closed as completed by niklaslong** 2022-11-08 10:15 UTC
Labels: bug, unconfirmed, testnet3
