### ISSUE TITLE
[Bug]Skipping an iteration of the puzzle (no connected peers)  DEBUG snarkos_node_router::handshake: Connecting to 34.168.118.156:4130... 2024-07-03T02:16:36.575195Z  WARN snarkos_node_router: Unable to connect to '34.168.118.156:4130' - '34.168.118.156:4130' disconnected before sending "Message::ChallengeResponse"

### ISSUE THREAD

**Issue by sinri12** [AleoHQ/snarkOS#3343] opened 2024-07-03 02:17 UTC
## 🐛 Bug Report
![화면 캡처 2024-07-03 111630](https://github.com/AleoNet/snarkOS/assets/72038993/d7b8d6aa-7aba-4a57-a50c-8225f5837332)

how to solve?

**Comment by T1murKO** [comment] 2024-07-03 07:39
+1

**Comment by ljedrz** [comment] 2024-07-03 07:43
Duplicate of https://github.com/AleoNet/snarkOS/issues/3340.

**Closed as completed by ljedrz** 2024-07-03 07:43 UTC
Labels: bug, duplicate
