### ISSUE TITLE
[Bug] inconsistency between block height in RPC and prometheus

### ISSUE THREAD

**Issue by unordered-set** [AleoHQ/snarkOS#964] opened 2021-07-21 23:16 UTC
## 🐛 Bug Report

This bug affects my monitoring a lot. So, when I'm checking block high like that:

```
curl -s --data-binary '{"jsonrpc": "2.0", "id":"1", "method": "getnodestats" }' -H 'content-type:application/json' http://localhost:3030/ | jq '.result.misc.block_height'
344264
```

it is 344264.

When I'm checking like that:

```
curl localhost:9000 | grep block_height
# TYPE snarkos_misc_block_height_total counter
snarkos_misc_block_height_total 1167399
```

## Expected Behavior
I am expecting these values to match

## Your Environment
snarkOS Version : 1.3.10

**Comment by unordered-set** [comment] 2021-07-21 23:22
Not sure about the reason, but looks like the logic for prometheus is like this:
1) initialize with current_block_height()
2) when we produced the block - increment the counter
3) when we receive the block - increment the counter

probably, both of 2) and 3) can happen in the orphaned state, that's why the number is too big

**Comment by ljedrz** [comment] 2021-07-22 07:55
Hi @unordered-set, and thanks for the report; are you by any chance running a node using the `master` branch? The current development branch is `staging`, and the exact issue you're describing has recently been fixed; it was tracked under https://github.com/AleoHQ/snarkOS/issues/782. I haven't been able to reproduce this with `staging` for a while now, so can you please clarify which branch resulted in this behavior?

**Comment by unordered-set** [comment] 2021-07-22 08:17
@ljedrz I am running my node on tags/v1.3.6 but let me switch to stage and check again.
Sorry for the inconvenience

**Comment by ljedrz** [comment] 2021-07-22 08:40
No worries at all; `master` is usually updated more often, but some major work is currently being done in snarkVM which has delayed this; you can see a draft PR adjusting snarkOS (and which will likely result in a new release) here: https://github.com/AleoHQ/snarkOS/pull/937.

**Comment by unordered-set** [comment] 2021-07-23 11:41
Not sure it is better in the stable branch:

```
root@Ubuntu-1804-bionic-64-minimal ~ # curl -s --data-binary '{"jsonrpc": "2.0", "id":"1", "method": "getnodestats" }' -H 'content-type:application/json' http://localhost:3030/ | jq '.result.misc.block_height'
0
root@Ubuntu-1804-bionic-64-minimal ~ # curl -s localhost:9000 | grep block_height# TYPE snarkos_misc_block_height_total gauge
snarkos_misc_block_height_total 179315
```

But now the issue is with RPC :)

**Comment by ljedrz** [comment] 2021-07-23 13:02
It's expected - the node tracks its metrics either via RPC or prometheus - there's no reason for the `getnodestats` call when you're using a nice `grafana` dashboard. You can check if the height is (more or less, depending on your scrape interval) the same as the one in the node's logs.

**Comment by ljedrz** [comment] 2021-07-23 17:53
It would be a good idea, however, to return an informative error response when a `prometheus`-enabled node receives the `getnodestats` RPC.

**Comment by howardwu** [comment] 2021-07-23 23:39
In case the issue is resolved in `staging`, I have prepared a PR to cut `v1.3.11` release.

**Comment by unordered-set** [comment] 2021-07-24 16:47
@ljedrz it looks like a pretty artifitial limitation for me, to be honest, I will check if I can fix it easily.
@howardwu , no, as I posted earlier, in `master` branch I saw inconsistencies, but in `staging` RPC was broken

**Comment by unordered-set** [comment] 2021-07-25 10:13
OK, more or less I get the idea how to fix it, but I don't actually think this issue should block a release @howardwu . This is an issue only for those who compile with `--features prometeus`, and I will try to fix it meanwhile

**Comment by ljedrz** [comment] 2021-07-26 07:56
>it looks like a pretty artifitial limitation for me, to be honest

The background is that in the past the RPC metrics were calculated separately using atomics and it would have been extra work for the node to keep track of them. This is not an issue anymore, as all the metrics are now aligned.

**Comment by ljedrz** [comment] 2021-07-26 10:01
Removing the `unconfirmed` label, as even though in the end this is not an inconsistency per se, not seeing the values of metrics in the RPC could be considered buggy behavior.

**Comment by ljedrz** [comment] 2021-07-30 06:33
Closed by https://github.com/AleoHQ/snarkOS/pull/982.

**Closed by ljedrz** 2021-07-30 06:33 UTC
Labels: RPC, bug, metrics
