### ISSUE TITLE
[Bug]canot connect to sync nodes

### ISSUE THREAD

**Issue by cszz12** [AleoHQ/snarkOS#1358] opened 2021-12-01 03:04 UTC
## 🐛 Bug Report
2021-12-01T03:02:54.637456Z TRACE Sending request for more peer connections
2021-12-01T03:02:54.637517Z TRACE Attempting connection to 143.198.166.150:4132...
2021-12-01T03:02:54.637556Z TRACE Attempting connection to 147.182.213.228:4132...
2021-12-01T03:02:54.637580Z TRACE Attempting connection to 137.184.192.155:4132...
2021-12-01T03:02:54.637591Z TRACE Attempting connection to 161.35.106.91:4132...
2021-12-01T03:02:54.637613Z TRACE Attempting connection to 159.223.118.35:4132...
2021-12-01T03:02:54.637626Z TRACE Attempting connection to 159.223.124.150:4132...
2021-12-01T03:02:54.637636Z TRACE Attempting connection to 157.245.133.62:4132...
2021-12-01T03:02:54.637649Z TRACE Attempting connection to 167.99.40.226:4132...
2021-12-01T03:02:54.637659Z TRACE Attempting connection to 188.166.7.13:4132...
2021-12-01T03:02:54.637678Z TRACE Skipping connection request to 143.198.166.150:4132 (tried 81 secs ago)
2021-12-01T03:02:54.637694Z TRACE Attempting connection to 165.232.145.194:4132...
2021-12-01T03:02:54.637707Z TRACE Attempting connection to 144.126.219.193:4132...
2021-12-01T03:02:54.637726Z TRACE Attempting connection to 143.198.164.241:4132...
2021-12-01T03:02:54.637758Z TRACE Attempting connection to 137.184.202.162:4132...
2021-12-01T03:02:54.637718Z TRACE Skipping connection request to 147.182.213.228:4132 (tried 81 secs ago)
2021-12-01T03:02:54.637805Z TRACE Skipping connection request to 137.184.192.155:4132 (tried 81 secs ago)
2021-12-01T03:02:54.637829Z TRACE Skipping connection request to 161.35.106.91:4132 (tried 81 secs ago)
2021-12-01T03:02:54.637860Z TRACE Skipping connection request to 159.223.118.35:4132 (tried 81 secs ago)
2021-12-01T03:02:54.637878Z TRACE Skipping connection request to 159.223.124.150:4132 (tried 81 secs ago)
2021-12-01T03:02:54.637886Z TRACE Skipping connection request to 167.99.40.226:4132 (tried 81 secs ago)
2021-12-01T03:02:54.637899Z TRACE Skipping connection request to 157.245.133.62:4132 (tried 81 secs ago)
2021-12-01T03:02:54.637905Z TRACE Skipping connection request to 188.166.7.13:4132 (tried 81 secs ago)
2021-12-01T03:02:54.637928Z TRACE Skipping connection request to 165.232.145.194:4132 (tried 81 secs ago)
2021-12-01T03:02:54.637942Z TRACE Skipping connection request to 144.126.219.193:4132 (tried 81 secs ago)
2021-12-01T03:02:54.637967Z TRACE Skipping connection request to 143.198.164.241:4132 (tried 81 secs ago)
2021-12-01T03:02:54.637979Z TRACE Skipping connection request to 137.184.202.162:4132 (tried 81 secs ago)
2021-12-01T03:03:03.638299Z DEBUG Status Report (type = Miner, status = Peering, block_height = 0, cumulative_weight = 0, block_requests = 0, connected_peers = 0)

(Write your description here)

## Steps to Reproduce

1. Step 1...
2. Step 2...
3. Step 3...

## Expected Behavior

(Write what you expected to happen here)

## Your Environment

- 
- 
- ubuntu

**Comment by cszz12** [comment] 2021-12-01 04:14
2021-12-01T04:13:39.117488Z TRACE Failed to get challenge response from 159.223.124.150:4132: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
2021-12-01T04:13:39.230957Z TRACE Failed to get challenge response from 143.198.166.150:4132: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
2021-12-01T04:13:39.271204Z TRACE Failed to get challenge response from 188.166.7.13:4132: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
2021-12-01T04:13:39.273758Z TRACE Failed to get challenge response from 157.245.133.62:4132: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
2021-12-01T04:13:39.274686Z TRACE Failed to get challenge response from 137.184.192.155:4132: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
2021-12-01T04:13:39.279394Z TRACE Failed to get challenge response from 159.223.118.35:4132: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
2021-12-01T04:13:39.404958Z TRACE Failed to get challenge response from 161.35.106.91:4132: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
2021-12-01T04:13:39.499176Z TRACE Failed to get challenge response from 167.99.40.226:4132: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
2021-12-01T04:13:47.046153Z DEBUG Status Report (type = Miner, status = Peering, block_height = 0, cumulative_weight = 0, block_requests = 0, connected_peers = 0)

**Comment by mostalt** [comment] 2021-12-01 10:50
same problem

**Comment by LasTshaMAN** [comment] 2021-12-01 16:17
Same for me, 

my 4132/tcp and 3032/tcp ports are reachable through the internet.

**Comment by cszz12** [comment] 2021-12-02 01:13
> Same for me,
> 
> my 4132/tcp and 3032/tcp ports are reachable through the internet.

weird, these are [sync nodes](https://github.com/AleoHQ/snarkOS/blob/8e75e9b8d917ee30a06123bf5f7c0a47fd19011d/src/environment/mod.rs) , they are reachable if I ping them, but cannot connect with snarkos

**Comment by zhaomin6666** [comment] 2021-12-03 02:19
> 

Yeah they are reachable if ping them. But it seems that port is not open. I don't know whetever it is problem about their firewall config. It's weird that they can be sync nodes when their port is not open.

**Comment by ljedrz** [comment] 2021-12-06 09:09
The sync nodes can be connected to (i.e. there is no general connectivity issue). I do think it would be a good idea to provide better information on why a connection attempt gets rejected or to verify if the node is routable as soon as it's started, though.

**Comment by ljedrz** [comment] 2021-12-10 16:19
Now that https://github.com/AleoHQ/snarkOS/pull/1397 is merged, have you perhaps seen an improvement?

**Comment by gjfrn** [comment] 2021-12-16 14:48
The ports are open but I'm having no luck connecting to peers. There is just a continual loop of "Attempting connection to ..." and then "Skipping connection request to ..."

There is also occasionally "Connecting to ..." followed by "Unable to reach '...': 'Elapsed(())'

2021-12-16T14:47:27.918452Z DEBUG Validating the ledger up to block 0 (0%)
2021-12-16T14:47:28.240301Z  INFO Ledger successfully loaded at block 0
2021-12-16T14:47:28.495331Z TRACE [Read-Only] Ledger successfully loaded at block 0
2021-12-16T14:47:28.557985Z  INFO Prover successfully initialized
2021-12-16T14:47:28.558240Z  INFO Listening for peers at 0.0.0.0:4132
2021-12-16T14:47:28.558344Z DEBUG Status Report (type = Miner, status = Peering, block_height = 0, cumulative_weight = 0, block_requests = 0, connected_peers = 0)
2021-12-16T14:47:28.558373Z TRACE Sending request for more peer connections
2021-12-16T14:47:28.558384Z TRACE Attempting connection to 159.223.118.35:4132...
2021-12-16T14:47:28.558389Z TRACE Attempting connection to 157.245.133.62:4132...
2021-12-16T14:47:28.558393Z TRACE Attempting connection to 143.198.166.150:4132...
2021-12-16T14:47:28.558398Z TRACE Attempting connection to 188.166.7.13:4132...
2021-12-16T14:47:28.558401Z TRACE Attempting connection to 167.99.40.226:4132...
2021-12-16T14:47:28.558404Z TRACE Attempting connection to 161.35.106.91:4132...
2021-12-16T14:47:28.558407Z TRACE Attempting connection to 147.182.213.228:4132...
2021-12-16T14:47:28.558410Z TRACE Attempting connection to 143.198.164.241:4132...
2021-12-16T14:47:28.558413Z TRACE Attempting connection to 144.126.219.193:4132...
2021-12-16T14:47:28.558415Z TRACE Attempting connection to 137.184.192.155:4132...
2021-12-16T14:47:28.558418Z TRACE Attempting connection to 165.232.145.194:4132...
2021-12-16T14:47:28.558423Z TRACE Attempting connection to 159.223.124.150:4132...
2021-12-16T14:47:28.558426Z TRACE Attempting connection to 137.184.202.162:4132...
2021-12-16T14:47:28.558486Z DEBUG Connecting to 137.184.202.162:4132...
2021-12-16T14:47:28.558551Z DEBUG Connecting to 159.223.118.35:4132...
2021-12-16T14:47:28.558573Z DEBUG Connecting to 157.245.133.62:4132...
2021-12-16T14:47:28.558588Z DEBUG Connecting to 143.198.166.150:4132...
2021-12-16T14:47:28.558604Z DEBUG Connecting to 188.166.7.13:4132...
2021-12-16T14:47:28.558618Z DEBUG Connecting to 167.99.40.226:4132...
2021-12-16T14:47:28.558631Z DEBUG Connecting to 161.35.106.91:4132...
2021-12-16T14:47:28.558644Z DEBUG Connecting to 147.182.213.228:4132...
2021-12-16T14:47:28.558657Z DEBUG Connecting to 143.198.164.241:4132...
2021-12-16T14:47:28.558670Z DEBUG Connecting to 144.126.219.193:4132...
2021-12-16T14:47:28.558682Z DEBUG Connecting to 137.184.192.155:4132...
2021-12-16T14:47:28.558694Z DEBUG Connecting to 165.232.145.194:4132...
2021-12-16T14:47:28.558706Z DEBUG Connecting to 159.223.124.150:4132...
2021-12-16T14:47:28.558760Z  INFO 

WELCOME MESSAGE REMOVED

2021-12-16T14:47:28.558810Z  INFO Mining Report (confirmed_blocks = 0, pending_blocks = 0, miner_address = aleo15x8rep0krh5ha5jhvt9s6hyp70yfpttva68y055a6flsjqdvaypsh0nk5m)
2021-12-16T14:47:29.059211Z ERROR Unable to reach '137.184.202.162:4132': 'Elapsed(())'
2021-12-16T14:47:29.060237Z ERROR Unable to reach '159.223.124.150:4132': 'Elapsed(())'
2021-12-16T14:47:29.060267Z ERROR Unable to reach '137.184.192.155:4132': 'Elapsed(())'
2021-12-16T14:47:29.060275Z ERROR Unable to reach '144.126.219.193:4132': 'Elapsed(())'
2021-12-16T14:47:29.060286Z ERROR Unable to reach '143.198.166.150:4132': 'Elapsed(())'
2021-12-16T14:47:29.060300Z ERROR Unable to reach '147.182.213.228:4132': 'Elapsed(())'
2021-12-16T14:47:29.060240Z ERROR Unable to reach '161.35.106.91:4132': 'Elapsed(())'
2021-12-16T14:47:29.060316Z ERROR Unable to reach '143.198.164.241:4132': 'Elapsed(())'
2021-12-16T14:47:29.060320Z ERROR Unable to reach '188.166.7.13:4132': 'Elapsed(())'
2021-12-16T14:47:29.060328Z ERROR Unable to reach '157.245.133.62:4132': 'Elapsed(())'
2021-12-16T14:47:29.060332Z ERROR Unable to reach '167.99.40.226:4132': 'Elapsed(())'
2021-12-16T14:47:29.060302Z ERROR Unable to reach '159.223.118.35:4132': 'Elapsed(())'
2021-12-16T14:47:29.060358Z ERROR Unable to reach '165.232.145.194:4132': 'Elapsed(())'
2021-12-16T14:47:37.559784Z DEBUG Status Report (type = Miner, status = Peering, block_height = 0, cumulative_weight = 0, block_requests = 0, connected_peers = 0)
2021-12-16T14:47:37.559847Z TRACE Sending request for more peer connections
2021-12-16T14:47:37.559863Z TRACE Attempting connection to 159.223.118.35:4132...
2021-12-16T14:47:37.559871Z TRACE Attempting connection to 157.245.133.62:4132...
2021-12-16T14:47:37.559874Z TRACE Attempting connection to 143.198.166.150:4132...
2021-12-16T14:47:37.559877Z TRACE Attempting connection to 188.166.7.13:4132...
2021-12-16T14:47:37.559880Z TRACE Attempting connection to 167.99.40.226:4132...
2021-12-16T14:47:37.559883Z TRACE Attempting connection to 161.35.106.91:4132...
2021-12-16T14:47:37.559891Z TRACE Attempting connection to 147.182.213.228:4132...
2021-12-16T14:47:37.559894Z TRACE Attempting connection to 143.198.164.241:4132...
2021-12-16T14:47:37.559899Z TRACE Attempting connection to 144.126.219.193:4132...
2021-12-16T14:47:37.559902Z TRACE Attempting connection to 137.184.192.155:4132...
2021-12-16T14:47:37.559904Z TRACE Attempting connection to 165.232.145.194:4132...
2021-12-16T14:47:37.559907Z TRACE Attempting connection to 159.223.124.150:4132...
2021-12-16T14:47:37.559910Z TRACE Attempting connection to 137.184.202.162:4132...
2021-12-16T14:47:37.559976Z TRACE Skipping connection request to 137.184.202.162:4132 (tried 9 secs ago)
2021-12-16T14:47:37.559986Z TRACE Skipping connection request to 159.223.118.35:4132 (tried 9 secs ago)
2021-12-16T14:47:37.559993Z TRACE Skipping connection request to 157.245.133.62:4132 (tried 9 secs ago)
2021-12-16T14:47:37.559997Z TRACE Skipping connection request to 143.198.166.150:4132 (tried 9 secs ago)
2021-12-16T14:47:37.560001Z TRACE Skipping connection request to 188.166.7.13:4132 (tried 9 secs ago)
2021-12-16T14:47:37.560004Z TRACE Skipping connection request to 167.99.40.226:4132 (tried 9 secs ago)
2021-12-16T14:47:37.560008Z TRACE Skipping connection request to 161.35.106.91:4132 (tried 9 secs ago)
2021-12-16T14:47:37.560011Z TRACE Skipping connection request to 147.182.213.228:4132 (tried 9 secs ago)
2021-12-16T14:47:37.560015Z TRACE Skipping connection request to 143.198.164.241:4132 (tried 9 secs ago)
2021-12-16T14:47:37.560018Z TRACE Skipping connection request to 144.126.219.193:4132 (tried 9 secs ago)
2021-12-16T14:47:37.560021Z TRACE Skipping connection request to 137.184.192.155:4132 (tried 9 secs ago)
2021-12-16T14:47:37.560025Z TRACE Skipping connection request to 165.232.145.194:4132 (tried 9 secs ago)
2021-12-16T14:47:37.560028Z TRACE Skipping connection request to 159.223.124.150:4132 (tried 9 secs ago)
2021-12-16T14:47:46.561637Z TRACE Sending request for more peer connections
2021-12-16T14:47:46.561677Z TRACE Attempting connection to 159.223.118.35:4132...
2021-12-16T14:47:46.561688Z TRACE Attempting connection to 157.245.133.62:4132...
2021-12-16T14:47:46.561694Z TRACE Attempting connection to 143.198.166.150:4132...
2021-12-16T14:47:46.561698Z TRACE Attempting connection to 188.166.7.13:4132...
2021-12-16T14:47:46.561707Z TRACE Attempting connection to 167.99.40.226:4132...
2021-12-16T14:47:46.561711Z TRACE Attempting connection to 161.35.106.91:4132...
2021-12-16T14:47:46.561715Z TRACE Attempting connection to 147.182.213.228:4132...
2021-12-16T14:47:46.561718Z TRACE Attempting connection to 143.198.164.241:4132...
2021-12-16T14:47:46.561721Z TRACE Attempting connection to 144.126.219.193:4132...
2021-12-16T14:47:46.561637Z DEBUG Status Report (type = Miner, status = Peering, block_height = 0, cumulative_weight = 0, block_requests = 0, connected_peers = 0)
2021-12-16T14:47:46.561724Z TRACE Attempting connection to 137.184.192.155:4132...
2021-12-16T14:47:46.561750Z TRACE Attempting connection to 165.232.145.194:4132...
2021-12-16T14:47:46.561754Z TRACE Attempting connection to 159.223.124.150:4132...
2021-12-16T14:47:46.561768Z TRACE Attempting connection to 137.184.202.162:4132...
2021-12-16T14:47:46.561779Z TRACE Skipping connection request to 143.198.166.150:4132 (tried 18 secs ago)
2021-12-16T14:47:46.561805Z TRACE Skipping connection request to 159.223.118.35:4132 (tried 18 secs ago)
2021-12-16T14:47:46.561822Z TRACE Skipping connection request to 161.35.106.91:4132 (tried 18 secs ago)
2021-12-16T14:47:46.561835Z TRACE Skipping connection request to 188.166.7.13:4132 (tried 18 secs ago)
2021-12-16T14:47:46.561847Z TRACE Skipping connection request to 167.99.40.226:4132 (tried 18 secs ago)
2021-12-16T14:47:46.561856Z TRACE Skipping connection request to 144.126.219.193:4132 (tried 18 secs ago)
2021-12-16T14:47:46.561866Z TRACE Skipping connection request to 147.182.213.228:4132 (tried 18 secs ago)
2021-12-16T14:47:46.561875Z TRACE Skipping connection request to 143.198.164.241:4132 (tried 18 secs ago)
2021-12-16T14:47:46.561885Z TRACE Skipping connection request to 165.232.145.194:4132 (tried 18 secs ago)
2021-12-16T14:47:46.561894Z TRACE Skipping connection request to 137.184.192.155:4132 (tried 18 secs ago)
2021-12-16T14:47:46.561903Z TRACE Skipping connection request to 157.245.133.62:4132 (tried 18 secs ago)
2021-12-16T14:47:46.561915Z TRACE Skipping connection request to 159.223.124.150:4132 (tried 18 secs ago)
2021-12-16T14:47:46.561924Z TRACE Skipping connection request to 137.184.202.162:4132 (tried 18 secs ago)

**Comment by web3judy** [comment] 2021-12-18 06:32
the problem still exists

**Comment by dannywitters** [comment] 2021-12-18 21:18
experiencing the same issue

**Comment by 0xZoomEye** [comment] 2021-12-19 06:12
same issue

**Comment by web3judy** [comment] 2021-12-24 02:18
If there is always Peering state, and can not connect to other nodes (for example, connect reset by peer error). The main reason for this is: the node you are connected to cannot access your machine's IP and the corresponding 4132 port number. So the best is the public IP, and then open the 4132 and 3032 ports in the firewall.

**Comment by fpaboim** [comment] 2021-12-31 16:19
> If there is always Peering state, and can not connect to other nodes (for example, connect reset by peer error). The main reason for this is: the node you are connected to cannot access your machine's IP and the corresponding 4132 port number. So the best is the public IP, and then open the 4132 and 3032 ports in the firewall.

Just to elaborate, I had to redirect traffic on my ISP's modem from wan 4132/tcp -> lan 4132/tcp; likewise for port 3032. You may have to do the same with your router if it's no functioning in bridge mode. Fixed the problem for me.

**Comment by liuzsen** [comment] 2022-01-07 03:00
# 🐛 Bug Report
log 
```2022-01-07T01:55:54.540535Z TRACE Received 'ChallengeRequest-B' from 165.232.145.194:4132
2022-01-07T01:55:54.540545Z TRACE Sending 'ChallengeResponse-B' to 165.232.145.194:4132
2022-01-07T01:55:54.561016Z TRACE Received 'ChallengeRequest-B' from 95.179.181.21:4132
2022-01-07T01:55:54.561032Z TRACE Sending 'ChallengeResponse-B' to 95.179.181.21:4132
2022-01-07T01:55:54.565325Z TRACE Received 'ChallengeRequest-B' from 159.223.124.150:4132
2022-01-07T01:55:54.565336Z TRACE Sending 'ChallengeResponse-B' to 159.223.124.150:4132
2022-01-07T01:55:54.578379Z TRACE Received 'ChallengeRequest-B' from 167.99.40.226:4132
2022-01-07T01:55:54.578391Z TRACE Sending 'ChallengeResponse-B' to 167.99.40.226:4132
2022-01-07T01:55:54.590337Z TRACE Received 'ChallengeRequest-B' from 144.126.219.193:4132
2022-01-07T01:55:54.590351Z TRACE Sending 'ChallengeResponse-B' to 144.126.219.193:4132
2022-01-07T01:55:54.642789Z TRACE Received 'ChallengeRequest-B' from 143.198.164.241:4132
2022-01-07T01:55:54.642805Z TRACE Sending 'ChallengeResponse-B' to 143.198.164.241:4132
2022-01-07T01:55:54.648233Z TRACE Received 'ChallengeRequest-B' from 159.223.118.35:4132
2022-01-07T01:55:54.648244Z TRACE Sending 'ChallengeResponse-B' to 159.223.118.35:4132
2022-01-07T01:55:54.660700Z TRACE Received 'ChallengeRequest-B' from 157.245.133.62:4132
2022-01-07T01:55:54.660716Z TRACE Sending 'ChallengeResponse-B' to 157.245.133.62:4132
2022-01-07T01:55:54.673119Z TRACE Received 'ChallengeRequest-B' from 147.182.213.228:4132
2022-01-07T01:55:54.673138Z TRACE Sending 'ChallengeResponse-B' to 147.182.213.228:4132
2022-01-07T01:55:54.678689Z TRACE Received 'ChallengeRequest-B' from 161.35.106.91:4132
2022-01-07T01:55:54.678702Z TRACE Sending 'ChallengeResponse-B' to 161.35.106.91:4132
2022-01-07T01:55:55.018258Z TRACE Failed to get challenge response from 137.184.202.162:4132: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
2022-01-07T01:55:55.029643Z TRACE Failed to get challenge response from 188.166.7.13:4132: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
2022-01-07T01:55:55.042162Z TRACE Failed to get challenge response from 165.232.145.194:4132: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
2022-01-07T01:55:55.063194Z TRACE Failed to get challenge response from 95.179.181.21:4132: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
2022-01-07T01:55:55.066302Z TRACE Failed to get challenge response from 159.223.124.150:4132: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
2022-01-07T01:55:55.079188Z TRACE Failed to get challenge response from 167.99.40.226:4132: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
2022-01-07T01:55:55.091725Z TRACE Failed to get challenge response from 144.126.219.193:4132: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
2022-01-07T01:55:55.143987Z TRACE Failed to get challenge response from 143.198.164.241:4132: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
2022-01-07T01:55:55.148897Z TRACE Failed to get challenge response from 159.223.118.35:4132: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
2022-01-07T01:55:55.161632Z TRACE Failed to get challenge response from 157.245.133.62:4132: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
2022-01-07T01:55:55.174501Z TRACE Failed to get challenge response from 147.182.213.228:4132: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
2022-01-07T01:55:55.179992Z TRACE Failed to get challenge response from 161.35.106.91:4132: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
2022-01-07T01:56:00.631181Z TRACE Received 'ChallengeRequest-B' from 137.184.192.155:4132
2022-01-07T01:56:00.631221Z TRACE Sending 'ChallengeResponse-B' to 137.184.192.155:4132
2022-01-07T01:56:01.133083Z TRACE Failed to get challenge response from 137.184.192.155:4132: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
2022-01-07T01:56:03.132286Z TRACE Sending request for more peer connections
2022-01-07T01:56:03.132314Z DEBUG Status Report (type = Miner, status = Peering, block_height = 0, cumulative_weight = 0, block_requests = 0, connected_peers = 0)
2022-01-07T01:56:03.132327Z TRACE Attempting connection to 143.198.164.241:4132...
2022-01-07T01:56:03.132373Z TRACE Attempting connection to 144.126.219.193:4132...
2022-01-07T01:56:03.132377Z TRACE Attempting connection to 147.182.213.228:4132...
2022-01-07T01:56:03.132381Z TRACE Attempting connection to 137.184.202.162:4132...
2022-01-07T01:56:03.132384Z TRACE Attempting connection to 143.198.166.150:4132...
2022-01-07T01:56:03.132388Z TRACE Attempting connection to 165.232.145.194:4132...
2022-01-07T01:56:03.132391Z TRACE Attempting connection to 157.245.133.62:4132...
2022-01-07T01:56:03.132394Z TRACE Attempting connection to 159.223.124.150:4132...
2022-01-07T01:56:03.132401Z TRACE Attempting connection to 188.166.7.13:4132...
2022-01-07T01:56:03.132405Z TRACE Attempting connection to 159.223.118.35:4132...
2022-01-07T01:56:03.132409Z TRACE Attempting connection to 167.99.40.226:4132...
2022-01-07T01:56:03.132412Z TRACE Attempting connection to 137.184.192.155:4132...
2022-01-07T01:56:03.132415Z TRACE Attempting connection to 161.35.106.91:4132...
2022-01-07T01:56:03.132437Z TRACE Skipping connection request to 144.126.219.193:4132 (tried 9 secs ago)
2022-01-07T01:56:03.132459Z TRACE Skipping connection request to 143.198.164.241:4132 (tried 9 secs ago)
2022-01-07T01:56:03.132464Z TRACE Skipping connection request to 137.184.202.162:4132 (tried 9 secs ago)
2022-01-07T01:56:03.132470Z TRACE Skipping connection request to 147.182.213.228:4132 (tried 9 secs ago)
2022-01-07T01:56:03.132476Z TRACE Skipping connection request to 143.198.166.150:4132 (tried 9 secs ago)
2022-01-07T01:56:03.132490Z TRACE Skipping connection request to 165.232.145.194:4132 (tried 9 secs ago)
2022-01-07T01:56:03.132510Z TRACE Skipping connection request to 159.223.124.150:4132 (tried 9 secs ago)
2022-01-07T01:56:03.132538Z TRACE Skipping connection request to 157.245.133.62:4132 (tried 9 secs ago)
2022-01-07T01:56:03.132565Z TRACE Skipping connection request to 188.166.7.13:4132 (tried 9 secs ago)
```
One small question, are the times in the logs correct? I used the date command to get this
```
mynode@mynode:~$ sudo hwclock --show && date -R
2022-01-07 10:58:31.759644+08:00
Fri, 07 Jan 2022 10:58:31 +0800
```

# Description
No matter what IP I connect to, I get this error

```
2022-01-07T01:55:55.018258Z TRACE Failed to get challenge response from 137.184.202.162:4132: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }
```
And I manually connected to some IP in this [mining pool](https://aleochain.io/nodes/miners), same error

I used nc to firm that 4132 port and 3032 is reachable

```
other@other:~$ nc -vz <my_node_ip> 4132
Connection to <my_node_ip> 4132 port [tcp/*] succeeded!
```

```
mynode@mynode:~$ sudo ufw status verbose
Status: active
Logging: on (low)
Default: deny (incoming), allow (outgoing), disabled (routed)
New profiles: skip

To                         Action      From
--                         ------      ----
4132/tcp                   ALLOW IN    Anywhere
3032/tcp                   ALLOW IN    Anywhere
22/tcp                     ALLOW IN    Anywhere
4132/tcp (v6)              ALLOW IN    Anywhere (v6)
3032/tcp (v6)              ALLOW IN    Anywhere (v6)
22/tcp (v6)                ALLOW IN    Anywhere (v6)
```
# Steps to  Reproduce
I followed steps of README reproduce this issue on several machine 

```
git clone https://github.com/AleoHQ/snarkOS.git --depth 1
cd snarkOS
./testnet2_ubuntu.sh
snarkos experimental new_account 
./run-miner.sh
```

# Environment
Ubuntu 20.04.3 LTS

**Comment by winlin** [comment] 2022-01-18 08:23
we find this issue too, in Windows 10, always get " Failed to get challenge response from xxxxx:4132: Os { code: 10054, kind: ConnectionReset, message: "远程主机强迫关闭了一个现有的连
接。" }"
we try the Ubuntu 20.04 still get the error: TRACE Failed to get challenge response from xxx.xxx: Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }

**Comment by ljedrz** [comment] 2022-03-01 08:32
Closing this issue, as it's not caused by the sync nodes, but by individual network setups of nodes connecting to them, and now we have disconnect reasons provided when a node's connection request gets rejected.

**Closed as completed by ljedrz** 2022-03-01 08:32 UTC
Labels: bug, network, testnet2
