### ISSUE TITLE
[Bug] snarkOS config.toml min/max peers are overwritten on start

### ISSUE THREAD

**Issue by evgeny-garanin** [AleoHQ/snarkOS#1249] opened 2021-10-31 21:22 UTC
## 🐛 Bug Report

Config.toml is overwritten to default values upon start.
You can't set miner address, min/max peers in the config. You can only set them in Exec line when you start snarkos.

## Steps to Reproduce

Set min/max peers in the config, start snarkos, check your peers settings via RPC call

## Expected Behavior

If you set min peers to 100 in the config, it is expected to have min peers =100 when checked via RPC.
Same for max peers, miner address

## Your Environment

-  1.3.17
-  up to date
-  Ubuntu 20.04

**Comment by aditya-manit** [comment] 2021-11-01 04:56
Duplicate of #1250 

Thanks @evgeny-garanin for creating the issue, I have also created one with some additional details, after reporting it on discord. You may close this one.

[Originally reported on discord here](https://discord.com/channels/700454073459015690/700477705422110761/904428900870930442)

**Comment by niklaslong** [comment] 2021-11-02 09:19
I've filed #1252 to address this issue—thank you for reporting this!

**Comment by ljedrz** [comment] 2022-02-08 10:43
Closing, as it's no longer applicable to testnet2.

**Closed as completed by ljedrz** 2022-02-08 10:43 UTC
Labels: bug
