### ISSUE TITLE
[Bug]timeout does not work

### ISSUE THREAD

**Issue by liujianghu** [AleoHQ/snarkOS#2046] opened 2022-11-10 09:41 UTC
## 🐛 Bug Report

- 
branch: testnet3
- 
- 
Checking the port when establishing a heartbeat does not work:

code: 
```
 if let Err(error) = timeout(
                                Duration::from_millis(Router::<N>::CONNECTION_TIMEOUT_IN_MILLIS),
                                TcpStream::connect(peer_ip),
                            )
                            .await
                            {
                                // Send the disconnect message.
                                let message =
                                    Message::Disconnect(DisconnectReason::YourPortIsClosed(listener_port).into());
                                outbound_socket.send(message).await?;
                                bail!("Unable to reach '{peer_ip}': '{:?}'", error);
                            }
```
use below to catch error: 
replace:
```
let res = timeout(
                    Duration::from_millis(1000),
                      TcpStream::connect(format!("127.0.0.1:4140")),
    );
    match res.await{
        Ok(data) => {
            match data {
                Ok(_) => info!("connect ok"),
                Err(err) => error!("connect fail").
            }
        },
        Err(error) => error!("task time out: {}", error),
    }
```

tks,

**Comment by niklaslong** [comment] 2022-11-10 10:19
Duplicate of #2040, please see the discussion there.

**Closed as completed by niklaslong** 2022-11-10 10:19 UTC
Labels: bug
