### ISSUE TITLE
[Bug] The reason why some solutions can not be relayed to the beacon

### ISSUE THREAD

**Issue by shannon-6block** [AleoHQ/snarkOS#2129] opened 2022-12-02 12:08 UTC
It's in [node/router/src/outbound.rs](https://github.com/AleoHQ/snarkOS/blob/testnet3/node/router/src/outbound.rs).
When a `UnconfirmedSolution` message calls `propogate()->send()->can_send()`, the `can_send()` function will return `false` when `propogate()` try to send the message to the 2nd peer.

**Comment by shannon-6block** [comment] 2022-12-02 12:17
So every time, the `UnconfirmedSolution` message can only propagate to the 1st peer in the peer list.

**Comment by HarukaMa** [comment] 2022-12-02 12:24
It seems the validators would only send the `UnconfirmedSolutions` to beacons (`propagate_to_beacons`, not `propagate`), and the validators are only allowed to connect to the official beacon (checked in `verify_challenge_request`). I think the current situation is not caused by this.

EDIT: unless somehow there are more than one official beacons and the official validators are connected to all of them. Not sure

However when we have more beacons this could be an issue though.

**Comment by shannon-6block** [comment] 2022-12-02 12:28
The `propagate_to_beacons()` will also send `UnconfirmedSolution` message to the 1st beacon only. When it tries to send the message to the 2nd beacon, the `can_send()` will return `false`.

**Comment by fhigher** [comment] 2022-12-02 12:51
Because the cache key uses the puzzle_ Commitment, the same commitment, will return the old timestamp. Therefore, starting from the second node, false will be returned

**Comment by howardwu** [comment] 2022-12-03 05:23
I have added PR #2134 which checks for duplicate solutions or transactions on a per IP address basis. Feel free to check if this change fixes the issue and can close the issue.

**Comment by 15012700225** [comment] 2022-12-04 01:16
The CPU load will drop to 0, intermittent.

**Comment by howardwu** [comment] 2022-12-04 19:56
Closing as the issue has been fixed with PR #2134.

**Closed as completed by howardwu** 2022-12-04 19:56 UTC
Labels: bug
