### ISSUE TITLE
Compilation Failure Due to Type Mismatch and Deprecated remove Method

### ISSUE THREAD

**Issue by SeloSlav** [AleoHQ/snarkOS#3071] opened 2024-02-08 18:14 UTC
My last bug was marked as closed, but I'm still unable to run a prover node on a fresh Ubuntu install, as of an hour ago. So here goes again:

🐛 Bug Report

I encountered a compilation failure while working with snarkOS. There are two primary issues noted:

    Deprecated usage of the remove method, which suggests using swap_remove instead to maintain map order.
    A type mismatch error (E0308), where a String was found when a Body was expected in an error handling function.

This bug prevents successful compilation of the snarkOS node and seems quite serious as it affects the fundamental operation of the software.
Steps to Reproduce

    Clone the snarkOS repository.
    Attempt to compile snarkOS using Rust.
    Observe the warnings about the deprecated remove method.
    Encounter the E0308 type mismatch error related to the .error_handler function expecting a Body type instead of a String.

Expected Behavior

The expected behavior is for snarkOS to compile without any errors or deprecation warnings. Instead of a String, the .error_handler should either be supplied with or be able to convert the provided string into a Body type, and the deprecated remove method should be updated to swap_remove.
Your Environment

    snarkOS Version: v2.2.7
    Rust Version: rustc 1.74.0 (79e9716c9 2023-11-13)
    Computer OS: Windows 10 Version 22H2 (OS Build 10945.3930)

**Comment by ljedrz** [comment] 2024-02-08 21:02
Please provide the output of the following: `git branch` and `git log | head -n 1` and the command you're using to install snarkOS.

**Comment by sujata-mahinder** [comment] 2024-02-09 02:33
I have the same issue. I tried using multiple different rustc version to solve the issue but it didn't work.
```

snarkOS Version: v2.2.7
Rust Version: rustc 1.76.0 (07dca489a 2024-02-04)
OS : ubuntu 22
```
```

Git branch - testnet3
Git log | head -n 1 - commit 937150eae125bd4d7c4b196d82acfe8f3390a035
```

Error while compiling -

```
Compiling snarkos-node-consensus v2.2.7 (/root/mit/snarkOS/node/consensus)
warning: `snarkos-node-bft` (lib) generated 5 warnings
   Compiling snarkos-node-rest v2.2.7 (/root/mit/snarkOS/node/rest)
error[E0308]: mismatched types
   --> node/rest/src/lib.rs:115:54
    |
115 |                 .error_handler(|error| Response::new(error.to_string()))
    |                                        ------------- ^^^^^^^^^^^^^^^^^ expected `Body`, found `String`
    |                                        |
    |                                        arguments to this function are incorrect
    |
note: associated function defined here
   --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/http-1.0.0/src/response.rs:253:12
    |
253 |     pub fn new(body: T) -> Response<T> {
    |            ^^^
help: call `Into::into` on this expression to convert `std::string::String` into `Body`
    |
115 |                 .error_handler(|error| Response::new(error.to_string().into()))
    |                                                                       +++++++

For more information about this error, try `rustc --explain E0308`.
error: could not compile `snarkos-node-rest` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

**Comment by ljedrz** [comment] 2024-02-09 09:06
As discussed in https://github.com/AleoHQ/snarkOS/issues/3070, the issue you're facing is most likely not plain compilation (which works fine due to the presence of the lockfile), or a scripted build (which is fixed now), but _running_ a node using the prover script (`run_prover.sh`), which attempts to perform aggressive updates.

A quick workaround is - as stated in that issues - deleting everything in that script from line 38 down; an adjustment to the script will be filed soon.

**Comment by ljedrz** [comment] 2024-02-09 11:45
I filed https://github.com/AleoHQ/snarkOS/pull/3075, which should remedy the issue as long as you're using the `run_prover.sh` script.

**Comment by samybg9** [comment] 2024-02-09 18:01
After 3 hours of trying i managed to run a prover Node. 

Here's what I had to: 
- Edit rust-toolchain: change version to 1.74.0, because of a dependance: [clap](https://github.com/clap-rs/clap) that can't run on the originally defined version 1.72.x. 
- Remove the update part of the script of `run_prover.sh` (Everything from line :38 down) 
- Edit file `node/rest/src/lib.rs` on line :115 changed 
`.error_handler(|error| Response::new(error.to_string()))`
to 
`.error_handler(|error| Response::new(error.to_string().into()))`
- Ran  `run_prover.sh` and got it to successfully start

This was done on Unbuntu 20.04

The devs didn't really make this one easy.

@ljedrz You might want to take a look at:
- The rust version and version of Clap that is being used 
- Run_prover script 
- Fix that type error 

I'd love to provide more feedback onece a new release is out. 

![image](https://github.com/AleoHQ/snarkOS/assets/79310871/e39c9fc3-4221-4a88-a10e-32b724efdbf3)

**Comment by ljedrz** [comment] 2024-02-09 18:11
The snarkOS repository currently doesn't use those dependencies in those versions, and the MSRV is `1.72.1` for now. Have you tried the change mentioned in https://github.com/AleoHQ/snarkOS/issues/3071#issuecomment-1935784418?

The affected dependencies and MSRV will likely be updated soon, but until then (and afterwards as well), the official lockfile needs to be obeyed.

**Comment by ljedrz** [comment] 2024-02-09 18:19
I see that you had edited the prover script using an earlier workaround; this means that you could still run it just fine, as long as you ran `cargo clean` first, which would allow you to restore your build to the default setup.

**Comment by SeloSlav** [comment] 2024-02-09 18:52
> The snarkOS repository currently doesn't use those dependencies in those versions, and the MSRV is `1.72.1` for now. Have you tried the change mentioned in [#3071 (comment)](https://github.com/AleoHQ/snarkOS/issues/3071#issuecomment-1935784418)?
> 
> The affected dependencies and MSRV will likely be updated soon, but until then (and afterwards as well), the official lockfile needs to be obeyed.

I tried a system reset and fresh install, but keep encountering this error when following the tutorial in the main documentation. Is there anything else you suggest I do?

**Comment by ljedrz** [comment] 2024-02-09 18:53
@SeloSlav just to be on the same page, which tutorial are you following?

**Comment by SeloSlav** [comment] 2024-02-09 18:54
> @SeloSlav just to be on the same page, which tutorial are you following?

This one: https://github.com/AleoHQ/snarkOS?tab=readme-ov-file#3-run-an-aleo-node

**Comment by ljedrz** [comment] 2024-02-09 18:59
Ok, so just to be sure that you have a clean slate, go to your snarkOS folder and:
1. run `cargo clean`
2. adjust the `run_prover.sh` script by either doing what PR https://github.com/AleoHQ/snarkOS/pull/3075 does, or removing everything starting from line 38

After this, the README instructions should work fine. Also, in the initial message you mentioned that your OS is  `Windows 10 Version 22H2 (OS Build 10945.3930)`; how do you build snarkOS? Are you sure you're using `build_ubuntu.sh`, under e.g. WSL?

**Comment by SeloSlav** [comment] 2024-02-09 19:02
I wrote down my OS incorrectly actually. I'm using Ubuntu on my VM.

I'll try the above.

**Closed as completed** 2024-02-09 21:55 UTC
Labels: bug, unconfirmed

**Comment by SeloSlav** [comment] 2024-02-10 23:36
![image](https://github.com/AleoHQ/snarkOS/assets/8828948/f76ea294-06a4-4fac-8a28-5f48221b44f8)

Reporting back. I ran cargo clean and removed everything from line 38 down in run-prover.sh but get a similar build error.

I'd like to run a node, but if I can't do this by following the instructions exactly as presented, is anyone else even able to?

**Comment by ljedrz** [comment] 2024-02-11 05:46
You seem to have not run `cargo clean`? Also, the branch has been updated in the meantime.

**Comment by SeloSlav** [comment] 2024-02-11 13:46
I did.

**Comment by ljedrz** [comment] 2024-02-11 14:20
While I can't reproduce your issue having done the following (and in that order):
- have an up to date local snarkOS repository
- run `cargo clean` inside it (i.e. there is no `target` folder inside)
- run `./build_ubuntu.sh`
- run `./run_prover.sh`

I can see that the repository is currently undergoing some heavy updates, so I'd wait for the next release before retrying.

**Comment by SeloSlav** [comment] 2024-02-11 14:33
Okay. I follow this exact instructions several times on fresh haven't been
able to run a successful client or prover node. So I'll wait until a new
release.
