### ISSUE TITLE
[Bug] run-miner.sh line 41: kill: .. - No such process

### ISSUE THREAD

**Issue by bendyarm** [AleoHQ/snarkOS#1389] opened 2021-12-07 08:32 UTC
## 🐛 Bug Report

After running fine for about 12 hours, I got this:
```
...
2021-12-07T06:26:17.327540Z TRACE Skipping 'UnconfirmedBlock 20954' from xxx
2021-12-07T06:26:17.892890Z TRACE Received 'Pong' from xxx
./run-miner.sh: line 41: kill: (119007) - No such process
Checking for updates...
No local changes to save
Running the node...
2021-12-07T06:26:22.024978Z TRACE Received 'Ping' from xxx
2021-12-07T06:26:22.059408Z TRACE Sending 'Pong' to xxx
    Finished release [optimized] target(s) in 0.08s
     Running `target/release/snarkos --miner ... --trial --verbosity 2`


         ╦╬╬╬╬╬╦
        ╬╬╬╬╬╬╬╬╬                    ▄▄▄▄        ▄▄▄
       ╬╬╬╬╬╬╬╬╬╬╬                  ▐▓▓▓▓▌       ▓▓▓
      ╬╬╬╬╬╬╬╬╬╬╬╬╬                ▐▓▓▓▓▓▓▌      ▓▓▓     ▄▄▄▄▄▄       ▄▄▄▄▄▄
     ╬╬╬╬╬╬╬╬╬╬╬╬╬╬╬              ▐▓▓▓  ▓▓▓▌     ▓▓▓   ▄▓▓▀▀▀▀▓▓▄   ▐▓▓▓▓▓▓▓▓▌
    ╬╬╬╬╬╬╬╜ ╙╬╬╬╬╬╬╬            ▐▓▓▓▌  ▐▓▓▓▌    ▓▓▓  ▐▓▓▓▄▄▄▄▓▓▓▌ ▐▓▓▓    ▓▓▓▌
   ╬╬╬╬╬╬╣     ╠╬╬╬╬╬╬           █▓▓▓▓▓▓▓▓▓▓█    ▓▓▓  ▐▓▓▀▀▀▀▀▀▀▀▘ ▐▓▓▓    ▓▓▓▌
  ╬╬╬╬╬╬╣       ╠╬╬╬╬╬╬         █▓▓▓▌    ▐▓▓▓█   ▓▓▓   ▀▓▓▄▄▄▄▓▓▀   ▐▓▓▓▓▓▓▓▓▌
 ╬╬╬╬╬╬╣         ╠╬╬╬╬╬╬       ▝▀▀▀▀      ▀▀▀▀▘  ▀▀▀     ▀▀▀▀▀▀       ▀▀▀▀▀▀
╚╬╬╬╬╬╩           ╩╬╬╬╬╩

Welcome to Aleo! We thank you for running a network node and supporting privacy.

Your Aleo address is ...

Starting a mining node on testnet2.


 ==================================================================================================

                         Welcome to Aleo Testnet2 - Incentivization Period
...
==================================================================================================

thread 'main' panicked at 'Failed to bind listener: Os { code: 98, kind: AddrInUse, message: "Address already in use" }. Check if another Aleo node is running', /home/mccarthy/snarkOS/src\
/network/server.rs:73:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2021-12-07T06:26:22.761658Z TRACE Received 'UnconfirmedBlock' from xxx
...
```

After that it seemed to do some sharing of blocks but it did not run PoSW any more
and it got slower and slower and got more and more errors.

When I followed the instructions here
https://github.com/AleoHQ/snarkOS/issues/1380#issuecomment-986817245
it went back to propagating blocks and trying to mine.

## Your Environment

- snarkos 2.0.0
- rustc 1.56.1
- OS: Linux Mint 20.2 Uma

**Comment by ljedrz** [comment] 2021-12-07 10:38
Thanks for the bug report! It's likely a duplicate of https://github.com/AleoHQ/snarkOS/issues/1380#issuecomment-986817245, but until it's certain, let's keep this one open.

Hmm, I'm wondering if it's not just a matter of the script not waiting enough for the shutdown / not ensuring that the running node is fully shut down before restarting.

**Comment by bendyarm** [comment] 2021-12-09 05:38
I'm still getting this error, maybe every 6 to 12 hours.

**Comment by bendyarm** [comment] 2021-12-14 17:13
I have not seen this error for about 5 days, so I'm thinking it has been fixed.

**Closed as completed** 2022-01-06 06:26 UTC
Labels: bug, likely fixed, testnet2
