### ISSUE TITLE
[Bug] Miner stops working and stuck in Shutting Down state

### ISSUE THREAD

**Issue by e4m7he6g** [AleoHQ/snarkOS#1380] opened 2021-12-05 13:24 UTC
## 🐛 Bug Report

Many nodes have same status for hours, **days**. My miners also affected
issue in v1 https://github.com/AleoHQ/snarkOS/issues/1177#issuecomment-942028241

all node list stuck (> 330) https://aleochain.io/graphql (thanks to team behind project for amazing tool)
```
{
  nodes(
    limit: 5
    filter: {
      message_version: 11
      node_type: MINER
      node_status: SHUTTING_DOWN
      is_alive: true
    }
    orderBy: { field: BLOCK_HEIGHT, direction: ASC }
  ) {
    summary {
      total
    }
    edges {
      ip
      block_height
      last_height_update
    }
  }
}
```

or here for charts
https://aleochain.io/checker?ip=75.119.136.3
35.230.113.77
178.62.200.144
47.90.252.198
161.97.163.89

## Steps to Reproduce
1. i dunno

## Expected Behavior
restart, start mining?

## Your Environment
- snarkOS 2.0.0 / 11 message version
- rustc 1.56.1 (59eed8a2a 2021-11-01)
- Debian 11/Ubuntu 20.04 (both)

**Comment by ljedrz** [comment] 2021-12-06 09:29
Are you able to reproduce this? The logs that are displayed right after the shutdown request would be most helpful.

**Comment by ljedrz** [comment] 2021-12-06 09:31
Also, please note that the issues not labeled as `testnet2` (like https://github.com/AleoHQ/snarkOS/issues/1177#issuecomment-942028241 which you linked) are only applicable to the node from testnet1.

**Comment by Ufukdogann** [comment] 2021-12-06 11:53
Hello all,

I have the same issue.

When I check my node IP in the morning, it was like this.

<img width="900" alt="Screenshot 2021-12-06 at 12 49 09" src="https://user-images.githubusercontent.com/8861458/144841009-f7888afa-67bc-4125-83f3-b59b2b0e7148.png">

The logs were like this,

<img width="1301" alt="Screenshot 2021-12-06 at 12 51 15" src="https://user-images.githubusercontent.com/8861458/144841257-f1b15524-6173-4755-9233-a04523ac8ad9.png">

Then I checked again my logs and the IP, the result of the IP still the same "ShuttingDown" however, my logs have changed like below

![photo_2021-12-06 12 49 50](https://user-images.githubusercontent.com/8861458/144841098-9da13c2c-f933-403a-a024-0dbb8ddb4b77.jpeg)

So, I am not sure does my node working well or not, can someone help me with that, please?

Best regards,

**Comment by ljedrz** [comment] 2021-12-06 14:17
I've been trying to reproduce this locally using dev nodes, but no luck yet. Due to that listener error, I suspect that it might be some issue with the script, but that one could potentially have been started a long time ago (it might have been updated in the meantime).

My suggestion for now is to:
1. shut down the node you're currently running
2. ensure that there are no other running instances by running `pgrep snarkos` (it should return nothing)
  - if `pgrep snarkos` does return numbers, run `kill -s SIGINT` for each of them (e.g. `kill -s SIGINT 12345`
  - run `pgrep snarkos` again, and if it still returns the numbers you run `kill -s SIGINT` with, use `kill -s SIGKILL` instead
  - [`pgrep snarkos` should no longer return anything]
3. run `git pull` to ensure your repo is up to date
4. start your node again following [the `README` instructions](https://github.com/AleoHQ/snarkOS#3a-run-an-aleo-client-node)

**Comment by gvsfans** [comment] 2021-12-07 18:44
I have same messages on at least 3/5 servers that i am running.

**Comment by howardwu** [comment] 2021-12-17 12:05
Closing as this issue should be fixed with the latest maps lock updates.

As it has been 10 days with no updates, please feel free to reopen if the issue has re-presented itself, and provide us with the Rust version and OS version.

**Closed as completed by howardwu** 2021-12-17 12:05 UTC
Labels: bug, likely fixed, testnet2
