### ISSUE TITLE
[Bug]run-client.sh cannot be compiled in windows environment

### ISSUE THREAD

**Issue by goodbabynow** [AleoHQ/snarkOS#1812] opened 2022-06-29 10:37 UTC
run-client.sh cannot be compiled in windows environment, stuck on 348-350 download, 2022.6.29

**Comment by feiyiban** [comment] 2022-06-29 15:22
so do i

**Comment by ljedrz** [comment] 2022-06-30 15:38
Closing as a duplicate of https://github.com/AleoHQ/snarkOS/issues/1620.

**Closed as completed by ljedrz** 2022-06-30 15:38 UTC
Labels: duplicate, windows, scripts, compilation
