### ISSUE TITLE
[Bug] Miner crash after started.

### ISSUE THREAD

**Issue by alar0n** [AleoHQ/snarkOS#1408] opened 2021-12-10 08:12 UTC
## 🐛 Bug Report

When i start miner i take this error:
...................
2021-12-10T08:00:56.763673Z DEBUG Validating the ledger up to block 22044 (88%)
2021-12-10T08:00:57.580233Z DEBUG Validating the ledger up to block 22545 (90%)
2021-12-10T08:00:57.831949Z DEBUG Validating the ledger up to block 23046 (92%)
2021-12-10T08:00:58.647720Z DEBUG Validating the ledger up to block 23547 (94%)
2021-12-10T08:00:58.900131Z DEBUG Validating the ledger up to block 24048 (96%)
2021-12-10T08:00:59.715947Z DEBUG Validating the ledger up to block 24549 (98%)
2021-12-10T08:00:59.968268Z DEBUG Validating the ledger up to block 25050 (100%)
thread 'main' panicked at 'assertion failed: `(left == right)`
left: `AleoLocator { hrp: "al", data: Fp256(2380939471054354564352380591945793932305172883044174739177983227110937361258) }`,
right: `AleoLocator { hrp: "al", data: Fp256(7903951354988248663872492897049527733470713583421970526936459737184403395962) }`', /home/*****/snarkOS/storage/src/state/ledger.rs:212:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

The day of the week before that worked fine.

## Your Environment

-  2.0.0
-  1.57.0
-  Ubuntu 20.10

**Comment by ljedrz** [comment] 2021-12-10 10:18
Closing as a duplicate of https://github.com/AleoHQ/snarkOS/issues/1375 (thanks for the report, though!).

**Closed as completed** 2021-12-10 10:31 UTC
Labels: bug, duplicate, crash, testnet2
