### ISSUE TITLE
Miner (prover) ditches operator node due to max connections

### ISSUE THREAD

**Issue by xorinox** [AleoHQ/snarkOS#1525] opened 2022-01-04 23:24 UTC
## 🐛 Bug Report

The prover ditches the operator node, due max connections. I think the operator node should be handled with priority and some other node should be discarded instead. 192.168.1.127:4011  is the operator node.

2022-01-04T23:02:29.278325Z  INFO Disconnecting from 192.168.1.127:4011 (exceeded maximum connections)
2022-01-04T23:02:38.278969Z  INFO Disconnecting from 192.168.1.127:4011 (exceeded maximum connections)
2022-01-04T23:02:59.333709Z  INFO Disconnecting from 192.168.1.127:4011 (peer has disconnected)
2022-01-04T23:03:01.312594Z  WARN Attempted to send to a non-connected peer 192.168.1.127:4011
2022-01-04T23:03:06.132672Z  WARN Attempted to send to a non-connected peer 192.168.1.127:4011
2022-01-04T23:03:07.135154Z  WARN Attempted to send to a non-connected peer 192.168.1.127:4011
2022-01-04T23:03:07.786012Z  WARN Attempted to send to a non-connected peer 192.168.1.127:4011
2022-01-04T23:03:08.135883Z  WARN Attempted to send to a non-connected peer 192.168.1.127:4011
2022-01-04T23:03:09.137017Z  WARN Attempted to send to a non-connected peer 192.168.1.127:4011
2022-01-04T23:03:10.138297Z  WARN Attempted to send to a non-connected peer 192.168.1.127:4011

## Steps to Reproduce

Let the prover long enough run, eventually it will disconnect from the operator node.

**Comment by xorinox** [comment] 2022-01-05 03:13
I worked around the issue by filtering out (hard coded) the operator IP in the network/peers.rs.  Around lines 336 and 360

                    // Proceed to send disconnect requests to these peers.
                    for peer_ip in peer_ips_to_disconnect {
                        if ! ("192.168.1.127:4011".eq(&peer_ip.to_string()) || "192.168.1.128:4012".eq(&peer_ip.to_string())) {
                            info!("Disconnecting from {} (exceeded maximum connections)", peer_ip);
                            self.send(peer_ip, Message::Disconnect).await;
                            // Add an entry for this `Peer` in the restricted peers.
                            self.restricted_peers.write().await.insert(peer_ip, Instant::now());
                        } else {
                            info!("...Didn't disconnect from {} due to (exceeded maximum connections line 343)", peer_ip);
                        }
                    }


                        if ! ("192.168.1.127:4011".eq(&peer_ip.to_string()) || "192.168.1.128:4012".eq(&peer_ip.to_string())) {
                            info!("Disconnecting from {} (exceeded maximum connections)", peer_ip);
                            self.send(peer_ip, Message::Disconnect).await;
                            // Add an entry for this `Peer` in the restricted peers.
                            self.restricted_peers.write().await.insert(peer_ip, Instant::now());
                        } else {
                            info!("...Didn't disconnect from {} due to (exceeded maximum connections line 366)", peer_ip);
                        }

**Comment by howardwu** [comment] 2022-01-06 02:25
Closing as this is a duplicate of #1518

**Closed as completed** 2022-01-06 02:26 UTC
Labels: bug
