### ISSUE TITLE
[Bug] Can't compile on Windows

### ISSUE THREAD

**Issue by heydo911** [AleoHQ/snarkOS#2294] opened 2023-03-19 16:39 UTC
error: failed to run custom build command for `librocksdb-sys v0.8.3+7.4.4`

Caused by:
  process didn't exit successfully: `D:\ALEOdm\snarkOS\target\release\build\librocksdb-sys-e662fd2cc4b1ccdd\build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['clang.dll', 'libclang.dll'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', 
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `snarkos v2.0.2 (D:\ALEOdm\snarkOS)`, intermediate artifacts can be found at `D:\ALEOdm\snarkOS\target`

**Comment by ljedrz** [comment] 2023-03-20 17:04
Duplicate of https://github.com/AleoHQ/snarkOS/issues/2199.

**Closed as completed by ljedrz** 2023-03-20 17:04 UTC
Labels: bug, duplicate, windows, compilation
