### ISSUE TITLE
could not compile snarkvm-ledger-store (lib) due to previous error

### ISSUE THREAD

**Issue by WeirdoPunk** [AleoHQ/snarkOS#3024] opened 2024-01-22 09:12 UTC
When I run cargo install -- path . Received error: could not compile signalvm ledger store (lib) due to previous error
Error: Failed to compile snakes v2.2.7 (/snarkOS), intermediate artifacts can be found at/snarkOS/target
To reuse those artifacts with a future compilation, set the environment variable CARGO_ TARGET_ DIR to that path

When I run again:
1. Cargo clean
2. export CARGO_ TARGET_ DIR=/snarkOS/target
3. Rustup update
4. Cargo install -- path
Still reporting error: could not compile signalvm ledger store (lib) due to previous error
Error: Failed to compile snakes v2.2.7 (/snarkOS), intermediate artifacts can be found at/snarkOS/target
To reuse those artifacts with a future compilation, set the environment variable CARGO_ TARGET_ DIR to that path

**Comment by ljedrz** [comment] 2024-01-23 18:55
Duplicate of https://github.com/AleoHQ/snarkOS/issues/3023.

**Closed as completed by ljedrz** 2024-01-23 18:55 UTC
Labels: bug, duplicate
