### ISSUE TITLE
[Bug]why run ./run-prover.sh is not success

### ISSUE THREAD

**Issue by sanshuipige** [AleoHQ/snarkOS#2061] opened 2022-11-14 15:36 UTC
## why run ./run-prover.sh is not success

error message : ERROR Unable to reach '161.35.24.55:4133': 'Elapsed(())'

**Comment by niklaslong** [comment] 2022-11-14 16:02
Duplicate of #2040.

**Closed as completed by niklaslong** 2022-11-14 16:02 UTC
Labels: bug
