### ISSUE TITLE
[Bug] thread 'main' panicked at 'Failed to start the node: Corruption: Corrupted compressed block contents: Snappy'

### ISSUE THREAD

**Issue by waynercheung** [AleoHQ/snarkOS#1636] opened 2022-02-15 03:57 UTC
When I run run-miner.sh,  I got the error message as:

thread 'main' panicked at 'Failed to start the node: Corruption: Corrupted compressed block contents: Snappy', src/main.rs:64:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

How can I fix it?

**Comment by shiziwen** [comment] 2022-02-15 04:08
I have got the same issue.
Even after I run `cargo run --release -- clean`

**Comment by ljedrz** [comment] 2022-02-15 08:06
The fact that this happens even after having cleared the storage is quite surprising, seems as if your build didn't support snappy as the storage compression method (while it's enabled by default); how did you build snarkOS? Did you use the guidelines from the README?

**Comment by shiziwen** [comment] 2022-02-15 10:16
@ljedrz It's quite surprising.
I have run the node for a long time.

How can I clear the storage manually?

**Comment by ljedrz** [comment] 2022-02-15 10:19
Remove `~/.aleo/storage`.

**Comment by shiziwen** [comment] 2022-02-15 10:37
The current path also has the storage, should I remove it?

**Comment by ljedrz** [comment] 2022-02-15 10:52
What current path? Inside the `snarkos` folder? That one is the source code for storage, no need to delete that one.

**Comment by shiziwen** [comment] 2022-02-16 03:28
> What current path? Inside the `snarkos` folder? That one is the source code for storage, no need to delete that one.

Thank you

**Comment by shiziwen** [comment] 2022-02-16 03:29
@ljedrz  another question, please.
How can I start the node from a snapshot? Because if I restart the node from the genesis block, it would cost a long time.

**Comment by ljedrz** [comment] 2022-02-16 09:20
https://aleo-testnet2-ledger.fra1.cdn.digitaloceanspaces.com/snapshot.tar.gz

**Comment by ljedrz** [comment] 2022-02-16 09:21
What was the end result? Were you able to wipe the storage and restart successfully? If yes, then I suspect this was a low-level storage corruption, perhaps caused by the node's process being terminated in an abrupt fashion.

**Comment by shiziwen** [comment] 2022-02-24 03:45
> What was the end result? Were you able to wipe the storage and restart successfully? If yes, then I suspect this was a low-level storage corruption, perhaps caused by the node's process being terminated in an abrupt fashion.

after I remove the storage and restart, it is success.

But after a few days, the error happens again.
I have to remove the storage and restart again.

So, what's the problem?

**Comment by shiziwen** [comment] 2022-02-24 03:48
> https://aleo-testnet2-ledger.fra1.cdn.digitaloceanspaces.com/snapshot.tar.gz

After I downloaded the snapshot, how can I start the node?
Put the snapshot to ~/.aleo/storage?

**Comment by shiziwen** [comment] 2022-02-24 03:52
@ljedrz

**Comment by shiziwen** [comment] 2022-02-24 04:05
@ljedrz  I have use the snapshot to start the node, there is also the problems:
thread 'main' panicked at 'Failed to start the node: Corruption: Corrupted compressed block contents: Snappy', src/main.rs:64:28
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I mv the resources  and storage decompressed from the snapshot to the ~/.aleo/.

**Comment by shiziwen** [comment] 2022-02-24 04:08
If you need any more details, please let me know.

**Comment by ljedrz** [comment] 2022-02-24 09:13
We're currently in the process of moving to the `testnet3` branch, which uses `LZ4` compression in the storage, and utilizes atomic batch writes, which removes `Snappy` and (hopefully all) possibility of storage corruption.

If you'd still like to tackle it in `testnet2`, storage is purely local, so you are free to apply [the atomic write batches PR](https://github.com/AleoHQ/snarkOS/pull/1542) to your local build, which would hopefully allow you to avoid these issues.

**Comment by shiziwen** [comment] 2022-02-24 09:23
As I know, the testnet2 has been ended, and I have run the nodes for a long time. 
So if the testnet3 will be available soon, I will wait for the testnet3.

Besides, I hope I can get the 125 reward tokens.

**Comment by ljedrz** [comment] 2022-03-01 09:36
Closing, as the issue is no longer applicable to the upcoming testnet3, which doesn't use Snappy.

**Closed as completed by ljedrz** 2022-03-01 09:36 UTC
Labels: bug, storage, crash
