### ISSUE TITLE
[Bug] The SnarkOS client panics syncing the ledger

### ISSUE THREAD

**Issue by pablodeymo** [AleoHQ/snarkOS#1933] opened 2022-09-16 15:30 UTC
## 🐛 Bug Report

The SnarkOS client panics syncing the ledger with the testnet3:

```

End: `new` took 836.708µs
2022-09-15T19:35:14.722878Z  INFO Synced up to block 1784 of 24872 - 7% complete (est. 21 minutes remaining)
2022-09-15T19:35:14.722919Z TRACE Requesting block 1884 of 24872
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Invalid block version', /Users/pablo/.cargo/git/checkouts/snarkos-749b83f411366d36/19181b1/snarkos/ledger/mod.rs:323:81
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: JoinError::Panic(Id(2602), ...)', /Users/pablo/.cargo/git/checkouts/snarkos-749b83f411366d36/19181b1/snarkos/ledger/mod.rs:344:22
```

## Steps to Reproduce

clone this repo (in the default branch testnet3) and run:

`cargo run --release`

## Your Environment

- snarkOS rev: 19181b1b529cfbc9a5b74ab5bf41fac1bf5cfafe
- Rust 1.63
- MacOS 12.6

**Comment by HarukaMa** [comment] 2022-09-19 07:34
This should be #1873.

**Comment by ljedrz** [comment] 2022-09-22 09:19
Closing as duplicate of https://github.com/AleoHQ/snarkOS/issues/1873.

**Closed as completed by ljedrz** 2022-09-22 09:19 UTC
Labels: bug, duplicate
