### ISSUE TITLE
[Bug] error.to_string() <-  expected `Body`, found `String` 

### ISSUE THREAD

**Issue by RickYoon** [AleoHQ/snarkOS#3062] opened 2024-02-06 10:12 UTC
## 🐛 Bug Report

I encountered a type mismatch error while compiling snarkOS. It seems that the error_handler function expects a Body type but received a String type instead.

This bug affects the compilation process of snarkOS and may impact the functionality of the affected components.

## Steps to Reproduce

1. Compile snarkOS using the provided build commands.
2. Observe the error message generated during compilation.

## Expected Behavior

The error_handler function should accept a String type argument without causing a type mismatch error.

## Your Environment

snarkOS Version: v2.2.7
Rust Version: rustc 1.75.0
Computer OS: ubuntu0.22.04.1

**Comment by ljedrz** [comment] 2024-02-06 10:35
Duplicate of https://github.com/AleoHQ/snarkOS/issues/3053.

**Closed as completed by ljedrz** 2024-02-06 10:35 UTC
Labels: bug, duplicate
